/*
-- 계정생성
CREATE USER C##SKILLMARKET IDENTIFIED BY "1234";
-- 권한부여
GRANT CONNECT, RESOURCE TO C##SKILLMARKET;
GRANT CREATE VIEW TO C##SKILLMARKET;
ALTER USER C##SKILLMARKET DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;
*/
/*
-- 카테고리 분류
대 1
중 2
소 3
--
*/
-- 시퀀스 제거
BEGIN
  FOR seq IN (SELECT sequence_name FROM user_sequences) LOOP
    EXECUTE IMMEDIATE 'DROP SEQUENCE ' || seq.sequence_name;
  END LOOP;
END;
/

-- 테이블 제거
BEGIN
  FOR tab IN (SELECT table_name FROM user_tables) LOOP
    EXECUTE IMMEDIATE 'DROP TABLE ' || tab.table_name || ' CASCADE CONSTRAINTS';
  END LOOP;
END;
/
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

-- 더미 시퀀스
CREATE SEQUENCE SEQ_CAT_LEVEL       INCREMENT BY 1 START WITH 1 MAXVALUE 3 CYCLE  NOCACHE;

-- DROP
/*
-- 테이블 제거
DROP TABLE "MEMBER"                 CASCADE CONSTRAINTS PURGE;
DROP TABLE "MEMBER_STATUS"          CASCADE CONSTRAINTS PURGE;
DROP TABLE "FREE_BOARD"             CASCADE CONSTRAINTS PURGE;
DROP TABLE "FREE_BOARD_COMMENT"     CASCADE CONSTRAINTS PURGE;
DROP TABLE "FREE_BOARD_LIKE"        CASCADE CONSTRAINTS PURGE;

DROP TABLE "WISH_LIST"              CASCADE CONSTRAINTS PURGE;
DROP TABLE "QNA"                    CASCADE CONSTRAINTS PURGE;
DROP TABLE "QNA_CATEGORY"           CASCADE CONSTRAINTS PURGE;
DROP TABLE "FREELANCER"             CASCADE CONSTRAINTS PURGE;
DROP TABLE "FREELANCER_CLASS"       CASCADE CONSTRAINTS PURGE;
DROP TABLE "CAREER"                 CASCADE CONSTRAINTS PURGE;
DROP TABLE "EDUCATION"              CASCADE CONSTRAINTS PURGE;

DROP TABLE "FREELANCER_QA"          CASCADE CONSTRAINTS PURGE;
DROP TABLE "FREELACNER_QA_REPLY"    CASCADE CONSTRAINTS PURGE;
DROP TABLE "QUOTATION"              CASCADE CONSTRAINTS PURGE;
DROP TABLE "QUOTATION_STATUS"       CASCADE CONSTRAINTS PURGE;
DROP TABLE "MESSAGE"                CASCADE CONSTRAINTS PURGE;
DROP TABLE "REQUEST"                CASCADE CONSTRAINTS PURGE;
DROP TABLE "REQUEST_CAT"            CASCADE CONSTRAINTS PURGE;
DROP TABLE "RECEIPT"                CASCADE CONSTRAINTS PURGE;
DROP TABLE "ALERT"                  CASCADE CONSTRAINTS PURGE;
DROP TABLE "ALERT_CAT"              CASCADE CONSTRAINTS PURGE;
DROP TABLE "ACCOUNT"                CASCADE CONSTRAINTS PURGE;
DROP TABLE "WITHDRAWAL_DETAIL"      CASCADE CONSTRAINTS PURGE;
DROP TABLE "DEPOSIT_DETAIL"        CASCADE CONSTRAINTS PURGE;
DROP TABLE "ESTIMATE"               CASCADE CONSTRAINTS PURGE;
DROP TABLE "ESTIMATE_CAT"           CASCADE CONSTRAINTS PURGE;
DROP TABLE "ESTIMATE_OPTION"        CASCADE CONSTRAINTS PURGE;
DROP TABLE "REVIEW"                 CASCADE CONSTRAINTS PURGE;
DROP TABLE "REVIEW_COMMENT"         CASCADE CONSTRAINTS PURGE;
DROP TABLE "ADMIN"                  CASCADE CONSTRAINTS PURGE;
DROP TABLE "ADMIN_RIGHTS"           CASCADE CONSTRAINTS PURGE;
DROP TABLE "REPORT"                 CASCADE CONSTRAINTS PURGE;
DROP TABLE "REPORT_CATEGORY"        CASCADE CONSTRAINTS PURGE;
DROP TABLE "QUESTION_ANSWER"        CASCADE CONSTRAINTS PURGE;
DROP TABLE "NOTICE"                 CASCADE CONSTRAINTS PURGE;
DROP TABLE "NOTICE_CATEGORY"        CASCADE CONSTRAINTS PURGE;
DROP TABLE "BANNER"                 CASCADE CONSTRAINTS PURGE;
DROP TABLE "FAQ"                    CASCADE CONSTRAINTS PURGE;
DROP TABLE "FAQ_CATEGORY"           CASCADE CONSTRAINTS PURGE;

DROP TABLE "ACCOUNT_DETAILS"        CASCADE CONSTRAINTS PURGE;
DROP TABLE ATTACHMENT;

DROP TABLE SALES_LOG                CASCADE CONSTRAINTS PURGE;
DROP TABLE SALES_CATEGORY           CASCADE CONSTRAINTS PURGE;

DROP TABLE PAYMENT_METHOD           CASCADE CONSTRAINTS PURGE;
DROP TABLE CASH_LOG                 CASCADE CONSTRAINTS PURGE;
DROP TABLE LOG_CATEGORY             CASCADE CONSTRAINTS PURGE;
DROP TABLE USER_CASH                CASCADE CONSTRAINTS PURGE;

DROP TABLE FREE_BOARD_CATEGORY      CASCADE CONSTRAINTS PURGE;
DROP TABLE QUOTATION_OPTION CASCADE CONSTRAINTS PURGE;
DROP TABLE ESTIMATE_FAQ CASCADE CONSTRAINTS PURGE;

-- 시퀀스 제거
DROP SEQUENCE SEQ_MEMBER                ;
DROP SEQUENCE SEQ_MEMBER_STATUS         ;
DROP SEQUENCE SEQ_FREE_BOARD            ;
DROP SEQUENCE SEQ_FREE_BOARD_COMMENT    ;
DROP SEQUENCE SEQ_USER_CASH        		;
DROP SEQUENCE SEQ_WISH_LIST             ;
DROP SEQUENCE SEQ_QNA                   ;
DROP SEQUENCE SEQ_QNA_CATEGORY          ;
DROP SEQUENCE SEQ_FREELANCER            ;
DROP SEQUENCE SEQ_FREELANCER_CLASS      ;
DROP SEQUENCE SEQ_CAREER                ;
DROP SEQUENCE SEQ_EDUCATION             ;

DROP SEQUENCE SEQ_FREELANCER_QA         ;
DROP SEQUENCE SEQ_FREELACNER_QA_REPLY   ;
DROP SEQUENCE SEQ_QUOTATION             ;
DROP SEQUENCE SEQ_QUOTATION_STATUS      ;
DROP SEQUENCE SEQ_MESSAGE               ;
DROP SEQUENCE SEQ_REQUEST               ;
DROP SEQUENCE SEQ_REQUEST_CAT           ;
DROP SEQUENCE SEQ_RECEIPT               ;
DROP SEQUENCE SEQ_ALERT                 ;
DROP SEQUENCE SEQ_ALERT_CAT             ;
DROP SEQUENCE SEQ_ACCOUNT               ;
DROP SEQUENCE SEQ_WITHDRAWAL_DETAIL     ;
DROP SEQUENCE SEQ_DEPOSIT_DETAIL        ;
DROP SEQUENCE SEQ_ESTIMATE              ;
DROP SEQUENCE SEQ_ESTIMATE_CAT          ;
DROP SEQUENCE SEQ_ESTIMATE_OPTION       ;
DROP SEQUENCE SEQ_REVIEW                ;
DROP SEQUENCE SEQ_REVIEW_COMMENT        ;
DROP SEQUENCE SEQ_ADMIN                 ;
DROP SEQUENCE SEQ_ADMIN_RIGHTS          ;
DROP SEQUENCE SEQ_REPORT                ;
DROP SEQUENCE SEQ_REPORT_CATEGORY       ;
DROP SEQUENCE SEQ_QUESTION_ANSWER       ;
DROP SEQUENCE SEQ_NOTICE                ;
DROP SEQUENCE SEQ_NOTICE_CATEGORY       ;
DROP SEQUENCE SEQ_BANNER                ;
DROP SEQUENCE SEQ_FAQ                   ;
DROP SEQUENCE SEQ_FAQ_CATEGORY          ;
DROP SEQUENCE SEQ_ACCOUNT_DETAILS       ;
DROP SEQUENCE SEQ_ATTACHMENT            ;

DROP SEQUENCE SEQ_SALES_LOG_NO          ;

DROP SEQUENCE SEQ_CASH_LOG_NO           ;

DROP SEQUENCE SEQ_ESTIMATE_FAQ ;


*/


-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

CREATE TABLE "MEMBER" (
	"MEMBER_NO"	            NUMBER		            NOT NULL,
	"STATUS_NO"	            CHAR(1)	DEFAULT 1	    NOT NULL,
	"MEMBER_ID"	            VARCHAR2(16)		    NOT NULL,
	"MEMBER_PWD"	        VARCHAR2(20)		    NOT NULL,
	"MEMBER_NICK"	        VARCHAR2(30)		    NOT NULL,
    "MEMBER_NAME"           VARCHAR2(20)            NOT NULL,
	"MEMBER_PHONE"	        CHAR(11)		                ,
	"MEMBER_EMAIL"	        VARCHAR2(100)		            ,
	"MEMBER_INTERST"	    VARCHAR2(100)		            ,
	"MEMBER_SIGN_DATE"	    TIMESTAMP	    DEFAULT SYSDATE	,
	"MEMBER_MODIFI_DATE"	TIMESTAMP	    DEFAULT SYSDATE	,
	"MEMBER_BANK"	        VARCHAR2(18)		            ,
	"MEMBER_ACCOUNT"	    VARCHAR2(100)		            ,
	"MEMBER_CASH"	        NUMBER		                    ,
	"MEMBER_PROFILE_PHOTO"	VARCHAR2(100)		            ,
	"MEMBER_NICK_STATUS"	CHAR(1)		    DEFAULT 'N'     ,
    "MEMBER_ADDRESS"	    VARCHAR2(100)		            
);


CREATE TABLE "MEMBER_STATUS" (
	"STATUS_NO"     	        NUMBER		        NOT NULL,
	"STATUS_NAME"	            VARCHAR2(10)		
);


CREATE TABLE "FREE_BOARD" (
	"BOARD_NO"	                NUMBER		        NOT NULL,
	"MEMBER_NO"	                NUMBER		        NOT NULL,
	"FREE_BOARD_TITLE"	        VARCHAR2(20)		        ,
	"FREE_BOARD_CONTENT"	    VARCHAR2(4000)		        ,
	"FREE_BOARD_ENROLL_DATE"	TIMESTAMP	 DEFAULT SYSDATE,
	"FREE_BOARD_EDIT_DATE"	    TIMESTAMP		            ,
	"FREE_BOARD_STATUS"	        CHAR(1)	DEFAULT '1'	NOT NULL,
	"FREE_BOARD_HIT"	        NUMBER		                ,
	"FREE_BOARD_LIKE"	        NUMBER		                ,
	FREE_BOARD_CATEGORY_NO      NUMBER
);


CREATE TABLE "FREE_BOARD_COMMENT" (
	"COMMENT_NO"	                NUMBER		    NOT NULL,
	"MEMBER_NO"	                    NUMBER		    NOT NULL,
	"BOARD_NO"	                    NUMBER		    NOT NULL,
	"REPLY_NO"	                    NUMBER		    NOT NULL,
	"COMMENT_CONTENT"	            VARCHAR2(100)		    ,
	"COMMENT_ENROLL_DATE"	        TIMESTAMP	  DEFAULT SYSDATE,
	"COMMENT_EDIT_DATE"	            TIMESTAMP	  DEFAULT SYSDATE,
	"COMMENT_STATUS"	            CHAR(1)		   DEFAULT 0
);


CREATE TABLE "FREE_BOARD_LIKE" (
    "LIKE_NO"                   NUMBER          NOT NULL,
	"MEMBER_NO"	                NUMBER		    NOT NULL,
	"BOARD_NO"	                NUMBER	 	    NOT NULL
);


--CREATE TABLE "USER_CASH" (
--    "MEMBER_NO"	                    NUMBER		    NOT NULL,
--    "CASH_POINT"	                NUMBER          DEFAULT 0,
--    "CASH_MONEY" 	                NUMBER          DEFAULT 0
--);


CREATE TABLE "WISH_LIST" (
	"MEMBER_NO"	                NUMBER		    NOT NULL,
	"ESTIMATE_NO"	            NUMBER		    NOT NULL
);


CREATE TABLE "QNA" (
	"QNA_NO"	        NUMBER		NOT NULL,
	"MEMBER_NO"	        NUMBER		NOT NULL,
	"QNA_CAT_NO"	    NUMBER		NOT NULL,
	"QNA_TITLE" 	    VARCHAR2(100)		,
	"QNA_CONTENT"	    VARCHAR2(4000)		,
	"QNA_ENROLLDATE"	TIMESTAMP		    ,
	"QNA_STATUS"	    CHAR(1)	DEFAULT  'Y'
);


CREATE TABLE "QNA_CATEGORY" (
	"QNA_CAT_NO"	    NUMBER		        NOT NULL,
	"QNA_CAT_NAME"	    VARCHAR2(100)		
);


CREATE TABLE "FREELANCER" (
	"FREELANCER_NO"	            NUMBER		    NOT NULL,
	"MEMBER_NO"	                NUMBER		    NOT NULL,
	"FREELANCER_CLASS_NO"	    NUMBER		    NOT NULL,
	"FREELANCER_INRODUCTION"	VARCHAR2(500)		    ,
	"FIELD_OF_EXPERTISE"	    VARCHAR2(200)		    ,
	"FREELANCER_CONTACT_TIME"	VARCHAR2(50)		    ,
	"FREELANCER_STATUS"	        CHAR(1)		DEFAULT 'Y' 
);


CREATE TABLE "FREELANCER_CLASS" (
	"FREELANCER_CLASS_NO"	    NUMBER		    NOT NULL,
	"FREELANCER_CLASS_NAME"	    VARCHAR2(30)		
);


CREATE TABLE "CAREER" (
	"CAREER_NO"	        NUMBER		NOT NULL,
	"FREELANCER_NO" 	NUMBER		NOT NULL,
	"CAREER_DATE"	    VARCHAR(15)         ,
	"CAREER_COMPANY"	VARCHAR(30)		    ,
	"CAREER_DEPT"	    VARCHAR(30)		    ,
	"CAREER_RESP"	    VARCHAR(30)		    ,
	"CAREER_LOCATION"	VARCHAR(15)		    ,
	"CAREER_EMP_DATE"	VARCHAR(15)			
);


CREATE TABLE "EDUCATION" (
	"EDU_NO"	        NUMBER		NOT NULL,
	"FREELANCER_NO"	    NUMBER		NOT NULL,
	"EDU_SCH"	        VARCHAR(72)		    ,
	"EDU_DEP"	        VARCHAR(72)		    ,
    "EDU_STATUS"        VARCHAR(12)
);





CREATE TABLE "FREELANCER_QA" (
	"F_QNA_NO"	                NUMBER		    NOT NULL,
	"MEMBER_NO"	                NUMBER		    NOT NULL,
	"ESTIMATE_NO"	            NUMBER		    NOT NULL,
	"F_QNA_TITLE"	            VARCHAR2(100)		    ,
	"F_QNA_CONTENT"	            VARCHAR2(4000)		    ,
	"F_QNA_ENROLL_DATE"	        TIMESTAMP		        ,
	"F_QNA_STATUS"	            CHAR(1)		
);


CREATE TABLE "FREELACNER_QA_REPLY" (
	"F_QNA_REPLY_NO"	        NUMBER		    NOT NULL,
	"F_QNA_NO"	                NUMBER		    NOT NULL,
	"F_QNA_REPLY_CONTENT"	    VARCHAR2(4000)		    ,
	"F_QNA_REPLY_ENROLL_DATE"	TIMESTAMP		        ,
	"F_QNA_REPLY_EDIT_DATE"	    TIMESTAMP		        ,
	"F_QNA_REPLY_STATUS"	    CHAR(1)		
);


CREATE TABLE "QUOTATION" (
    "QUOTATION_NO"                      NUMBER          NOT NULL,
    "ESTIMATE_NO"                       NUMBER          NOT NULL,
    "QUOTATION_PREV_VER"                NUMBER                  ,
    "MEMBER_NO"                         NUMBER          NOT NULL,
    "QUOTATION_STATUS_NO"               NUMBER          NOT NULL,
    "QUOTATION_PRICE"                   NUMBER                  ,
    "QUOTATION_PERIOD"                  VARCHAR2(100)           ,
    "PAYMENT_METHOD_NO"                 NUMBER          NOT NULL,
    "QUOTATION_ENROLL_DATE"             TIMESTAMP               ,
    "QUOTATION_MODIFICATION_DATE"       TIMESTAMP      
);


-- 주문서 상태
CREATE TABLE "QUOTATION_STATUS" (
   "QUOTATION_STATUS_NO"       NUMBER          NOT NULL,
   "QUOTATION_STATUS_NAME"       VARCHAR2(100)      
);


-- 주문한 옵션
CREATE TABLE "QUOTATION_OPTION" (
    QUOTATION_OPTION_NO         NUMBER  NOT NULL,
    QUOTATION_NO                NUMBER  NOT NULL,
    ESTIMATE_OPTION_NO          NUMBER  NOT NULL,
    QUOTATION_OPTION_QUANTITY   NUMBER
);


CREATE TABLE "MESSAGE" (
	"MAIL_NO"	        NUMBER		        NOT NULL,
	"QUOTATION_NO"	    NUMBER		        NOT NULL,
	"MEMBER_NO2"	    NUMBER		        NOT NULL,
	"REQUEST_NO"	    NUMBER		        NOT NULL,
	"MAIL_TITLE"	    VARCHAR2(10)		        ,
	"MAIL_CONTENT"	    VARCHAR2(4000)		        ,
	"MAIL_FILE"	        VARCHAR2(4000)		        ,
	"MAIL_ENROLL_DATE"	TIMESTAMP		            ,
	"MAIL_CHECK"	    CHAR(1)	DEFAULT 0   NOT NULL,
	"MAIL_STATUS"	    CHAR(1)		
);


CREATE TABLE "REQUEST" (
	"REQUEST_NO"	        NUMBER		    NOT NULL,
	"REQUEST_CAT_NO"	    NUMBER		    NOT NULL,
	"QUOTATION_NO"	        NUMBER		    NOT NULL,
	"REQUEST_CONSENT"	    CHAR(1)		            ,
	"REQUEST_PRICE"     	NUMBER		            ,
	"REQUEST_PERIOD"	    VARCHAR2(100)		
);


CREATE TABLE "REQUEST_CAT" (
	"REQUEST_CAT_NO"	        NUMBER		    NOT NULL,
	"REQUEST_CAT_NAME"	        VARCHAR2(30)		
);


CREATE TABLE "RECEIPT" (
	"RECEIPT_NO"	            NUMBER		    NOT NULL,
	"QUOTATION_NO"	            NUMBER		    NOT NULL,
	"RECEIPT_ENROLL_DATE"	    VARCHAR2(100)		    ,
	"RECEIPT_PRICE"	            NUMBER		
);


CREATE TABLE "ALERT" (
	"ALERT_NO"	        NUMBER		NOT NULL,
	"MEMBER_NO"	        NUMBER		NOT NULL,
	"MEMBER_NO2"	    NUMBER		NOT NULL,
	"ALERT_CAT_NO"	    NUMBER		NOT NULL,
	"MAIL_NO"	        NUMBER		NOT NULL,
	"ALERT_STATUS"	    CHAR(1)		
);


CREATE TABLE "ALERT_CAT" (
	"ALERT_CAT_NO"	        NUMBER		    NOT NULL,
	"ALERT_CAT_NAME"	    VARCHAR2(10)		
);


CREATE TABLE "ACCOUNT" (
	"TRANSACTION_ID"	        NUMBER		    NOT NULL,
	"DEPOSTI_NO"	            NUMBER		    NOT NULL,
	"WITHDRWAL_ID"	            NUMBER		    NOT NULL,
	"BALANCE"	                NUMBER		
);


CREATE TABLE "WITHDRAWAL_DETAIL" (
	"WITHDRWAL_ID"	            NUMBER		    NOT NULL,
	"RECEIVER"	                VARCHAR2(50)	        ,
	"WITHDRWAL_AMOUNT"	        NUMBER		            ,
	"WITHDRAWAL_RSN"	        VARCHAR2(100)		
);


CREATE TABLE "DEPOSIT_DETAIL" (
	"DEPOSIT_NO"	            NUMBER		    NOT NULL,
	"PAYER"	                    VARCHAR2(50)	        ,
	"DEPOSIT_AMOUNT"	        NUMBER		            ,
	"DEPOSIT_RSH"	            VARCHAR2(100)		
);


CREATE TABLE "ESTIMATE" (
	"ESTIMATE_NO"	                NUMBER		    NOT NULL,
	"FREELANCER_NO"	                NUMBER		    NOT NULL,
	"ESTIMATE_CAT_NO"	            NUMBER		    NOT NULL,
	"ESTIMATE_TITLE"	            VARCHAR2(300)		    ,
    "ESTIMATE_DURATION"	            VARCHAR2(300)		    ,
	"ESTIMATE_THUMBNAIL"	        VARCHAR2(100)		    ,
	"ESTIMATE_LINE_INTRODUCTION"	VARCHAR2(1500)		    ,
	"ESTIMATE_PRICE"	            NUMBER		            ,
	"ESTIMATE_DETAIL"	            VARCHAR2(4000)		    ,
	"ESTIMATE_DETAIL_FILE"	        VARCHAR2(4000)		    ,
	"ESTIMATE_PORTFOLIO"	        VARCHAR2(100)		    ,
	"BUSINESS_REGISTRATION_NUMBER"	VARCHAR2(10)		    ,
	"ESTIMATE_ENROLL_DATE"	        TIMESTAMP   DEFAULT SYSDATE		        ,
	"ESTIMATE_MODIFICATION_DATE"	TIMESTAMP		        ,
	"ESTIMATE_STATUS"	            CHAR(1)		 ,
	"ESTIMATE_VIEWS"	            NUMBER		
);


CREATE TABLE "ESTIMATE_CAT" (
	"ESTIMATE_CAT_NO"	                NUMBER		    NOT NULL,
	"ABOVE_CAT_NO"	                    NUMBER		    NOT NULL,
	"ESTIMATE_CAT_NAME"	                VARCHAR2(60)		    ,
	"ESTIMATE_CAT_SCOPE"	            VARCHAR2(3)             ,
    "ESTIMATE_CAT_FILE"                 VARCHAR2(100)
);


CREATE TABLE "ESTIMATE_OPTION" (
	"ESTIMATE_OPTION_NO"	        NUMBER		    NOT NULL,
	"ESTIMATE_NO"	                NUMBER		    NOT NULL,
	"ESTIMATE_OPTION_NAME"	        VARCHAR2(200)		    ,
	"ESTIMATE_OPTION_PRICE"	        NUMBER		            ,
	"ESTIMATE_OPTION_QUANTITY"	    NUMBER		
);


CREATE TABLE "REVIEW" (
	"REVIEW_NO"	                    NUMBER		    NOT NULL,
	"ESTIMATE_NO"	                NUMBER		    NOT NULL,
	"MEMBER_NO"	                    NUMBER		    NOT NULL,
	"REVIEW_CONTENT"	            VARCHAR2(500)		    ,
	"REVIEW_PHOTO"	                VARCHAR2(100)		    ,
	"REVIEW_RATING"	                NUMBER		            ,
	"REVIEW_ENROLL_DATE"	        TIMESTAMP		        ,
	"REVIEW_MODIFICATION_DATE"	    TIMESTAMP		        ,
	"REVIEW_STATUS"             	CHAR(1)		
);


CREATE TABLE "REVIEW_COMMENT" (
	"REVIEW_COMMENT_NO"	                NUMBER		    NOT NULL,
	"REVIEW_NO"	                        NUMBER		    NOT NULL,
	"NUM"	                            NUMBER		    NOT NULL,
	"REVIEW_COMMENT_CONTENT"	        VARCHAR2(500)		    ,
	"REVIEW_COMMENT_ENROLL_DATE"	    TIMESTAMP		        ,
	"REVIEW_COMMENT_MODIFICATION_DATE"	TIMESTAMP		        ,
	"REVIEW_COMMENT_STATUS"	            CHAR(1)		
);


CREATE TABLE "ADMIN" (
	"ADMIN_NO"	    NUMBER		    NOT NULL,
	"ADMIN_GR_NO"	NUMBER		    NOT NULL,
	"ADMIN_ID"	    VARCHAR2(16)	    	,
	"ADMIN_PWD"	    VARCHAR2(20)		    ,
	"ADMIN_NICK"	VARCHAR2(30)		
);


CREATE TABLE "ADMIN_RIGHTS" (
	"ADMIN_RIGHTS_NO"	            NUMBER		    NOT NULL,
	"ADMIN_RIGHTS_NAME"	            VARCHAR2(20)		
);


CREATE TABLE "REPORT" (
	"RPT_NO"	        NUMBER		    NOT NULL,
	"RPTCAT_NO"	        NUMBER		    NOT NULL,
	"MEMBER_NO"	        NUMBER		    NOT NULL,
	"MEMBER_NO_BAD"	    NUMBER		    NOT NULL,
	"RPT_TITLE"	        VARCHAR2(100)		    ,
	"RPT_CONTENT"	    VARCHAR2(4000)		    ,
    "RPT_STATUS"        CHAR(1)	DEFAULT 'N'   NOT NULL          
);


CREATE TABLE "REPORT_CATEGORY" (
	"RPT_CAT_NO"	            NUMBER		    NOT NULL,
	"RPT_CAT_NAME"	            VARCHAR2(100)		
);


CREATE TABLE "QUESTION_ANSWER" (
	"QUESTION_ANSWER_NO"	        NUMBER		    NOT NULL,
	"ADMIN_NO"	                    NUMBER		    NOT NULL,
	"QNA_NO"	                    NUMBER		    NOT NULL,
	"QUESTION_ANSWER_CONTENT"	    VARCHAR2(4000)		    ,
	"QUESTION_ANSWER_ENROLLDATE"	TIMESTAMP		
);


CREATE TABLE "NOTICE" (
	"NOTI_NO"	        NUMBER		           NOT NULL,
	"NOTI_CAT_NO"	    NUMBER		           NOT NULL,
	"ADMIN_NO"	        NUMBER		           NOT NULL,
	"NOTI_TITLE"	    VARCHAR2(100)                  ,
	"NOTI_CONTENT"	    VARCHAR2(4000)		           ,
	"NOTI_ENROLLDATE"	TIMESTAMP	    DEFAULT SYSDATE,
	"NOTI_MODIFYDATE"	TIMESTAMP	    DEFAULT SYSDATE,
	"NOTI_STATUS"	    CHAR(1)		    DEFAULT     'Y',
	"NOTI_HIT"	        NUMBER	DEFAULT 0      NOT NULL
);


CREATE TABLE "NOTICE_CATEGORY" (
	"NOTI_CAT_NO"	            NUMBER		    NOT NULL,
	"NOTI_CAT_NAME"	            VARCHAR2(100)		
);


CREATE TABLE "BANNER" (
	"BANNER_NO"	                    NUMBER		NOT NULL,
	"BANNER_BACKGROUNDCOLOR"        VARCHAR2(100)       ,
	"BANNER_FILE"	                VARCHAR2(100)		,
	"BANNER_ENROLLDATE"	            TIMESTAMP	DEFAULT SYSDATE,	  
    "BANNER_STATUS"	                CHAR(1)
);


CREATE TABLE "FAQ" (
	"FAQ_NO"	        NUMBER		NOT NULL,
	"ADMIN_NO"	        NUMBER		NOT NULL,
	"FAQ_CAT_NO"	    NUMBER		NOT NULL,
	"FAQ_TITLE"	        VARCHAR2(100)		,
	"FAQ_Q_CONTENT"	    VARCHAR2(4000)		,
	"FAQ_A_CONTENT"	    VARCHAR2(4000)		,
	"FAQ_STATUS"	    CHAR(1)		        ,
	"FAQ_HIT"	        NUMBER		        ,
	"FAQ_ENROLLDATE"	TIMESTAMP		    ,
	"FAQ_MODIFYDATE"	TIMESTAMP		
);


CREATE TABLE "FAQ_CATEGORY" (
	"FAQ_CAT_NO"	            NUMBER		    NOT NULL,
	"FAQ_CAT_NAME"	            VARCHAR2(100)		
);

CREATE TABLE "ACCOUNT_DETAILS" (
	"Key"	VARCHAR(255)		NOT NULL
);

CREATE TABLE "ATTACHMENT" (
	"ATTACHMENT_NO"				NUMBER			NOT NULL,
	"ESTIMATE_NO"				NUMBER			NOT NULL,
	"ATTACHMENT_INSERT_TIME"	TIMESTAMP		NOT NULL,
	"ATTACHMENT_DELETE_TIME"	TIMESTAMP		NULL,
	"ATTACHMENT_ORIGIN_NAME"	VARCHAR2(300)	NOT NULL,
	"ATTACHMENT_SERVER_NAME"	VARCHAR2(50)	NOT NULL,
	"ATTACHMENT_TYPE"			VARCHAR2(40)	NOT NULL
);

CREATE TABLE "FREE_BOARD_CATEGORY" (
    "FREE_BOARD_CATEGORY_NO"    NUMBER NOT NULL,
    "FREE_BOARD_CATEGORY_NAME"    VARCHAR2(50)
);



CREATE TABLE ESTIMATE_FAQ (
    ESTIMATE_FAQ_NO NUMBER NOT NULL,
    ESTIMATE_NO NUMBER NOT NULL,
    ESTIMATE_FAQ_Q_CONTENT VARCHAR2(200) NULL,
    ESTIMATE_FAQ_A_CONTENT VARCHAR2(200) NULL,
    ESTIMATE_FAQ_STATUS CHAR(1) NULL,
    ESTIMATE_FAQ_ENROLLDATE TIMESTAMP NULL,
    ESTIMATE_FAQ_MODIFY_DATE TIMESTAMP NULL,
    CONSTRAINT PK_ESTIMATE_FAQ PRIMARY KEY (ESTIMATE_FAQ_NO)
);


CREATE SEQUENCE SEQ_ESTIMATE_FAQ ;







--/시퀀스생성
CREATE SEQUENCE SEQ_MEMBER                INCREMENT BY 1 START WITH 100 NOCACHE;
CREATE SEQUENCE SEQ_MEMBER_STATUS         INCREMENT BY 1 START WITH 1   NOCACHE;
CREATE SEQUENCE SEQ_FREE_BOARD            INCREMENT BY 1 START WITH 100 NOCACHE;
CREATE SEQUENCE SEQ_FREE_BOARD_COMMENT    INCREMENT BY 1 START WITH 100 NOCACHE;
CREATE SEQUENCE SEQ_USER_CASH        	  INCREMENT BY 1 START WITH 100 NOCACHE;
CREATE SEQUENCE SEQ_WISH_LIST             INCREMENT BY 1 START WITH 100 NOCACHE;
CREATE SEQUENCE SEQ_QNA                   INCREMENT BY 1 START WITH 100 NOCACHE;
CREATE SEQUENCE SEQ_QNA_CATEGORY          INCREMENT BY 1 START WITH 100 NOCACHE;
CREATE SEQUENCE SEQ_FREELANCER            INCREMENT BY 1 START WITH 100 NOCACHE;
CREATE SEQUENCE SEQ_FREELANCER_CLASS      INCREMENT BY 1 START WITH 1   NOCACHE;
CREATE SEQUENCE SEQ_CAREER                INCREMENT BY 1 START WITH 100 NOCACHE;
CREATE SEQUENCE SEQ_EDUCATION             INCREMENT BY 1 START WITH 100 NOCACHE;

CREATE SEQUENCE SEQ_FREELANCER_QA         INCREMENT BY 1 START WITH 100 NOCACHE;
CREATE SEQUENCE SEQ_FREELACNER_QA_REPLY   INCREMENT BY 1 START WITH 100 NOCACHE;
CREATE SEQUENCE SEQ_QUOTATION             INCREMENT BY 1 START WITH 100 NOCACHE;
CREATE SEQUENCE SEQ_QUOTATION_STATUS      INCREMENT BY 1 START WITH 100 NOCACHE;
CREATE SEQUENCE SEQ_MESSAGE               INCREMENT BY 1 START WITH 100 NOCACHE;
CREATE SEQUENCE SEQ_REQUEST               INCREMENT BY 1 START WITH 100 NOCACHE;
CREATE SEQUENCE SEQ_REQUEST_CAT           INCREMENT BY 1 START WITH 100 NOCACHE;
CREATE SEQUENCE SEQ_RECEIPT               INCREMENT BY 1 START WITH 100 NOCACHE;
CREATE SEQUENCE SEQ_ALERT                 INCREMENT BY 1 START WITH 100 NOCACHE;
CREATE SEQUENCE SEQ_ALERT_CAT             INCREMENT BY 1 START WITH 100 NOCACHE;
CREATE SEQUENCE SEQ_ACCOUNT               INCREMENT BY 1 START WITH 100 NOCACHE;
CREATE SEQUENCE SEQ_WITHDRAWAL_DETAIL     INCREMENT BY 1 START WITH 100 NOCACHE;
CREATE SEQUENCE SEQ_DEPOSIT_DETAIL        INCREMENT BY 1 START WITH 100 NOCACHE;
CREATE SEQUENCE SEQ_ESTIMATE              INCREMENT BY 1 START WITH 100 NOCACHE;
CREATE SEQUENCE SEQ_ESTIMATE_CAT          INCREMENT BY 1 START WITH 100 NOCACHE;
CREATE SEQUENCE SEQ_ESTIMATE_OPTION       INCREMENT BY 1 START WITH 100 NOCACHE;
CREATE SEQUENCE SEQ_REVIEW                INCREMENT BY 1 START WITH 100 NOCACHE;
CREATE SEQUENCE SEQ_REVIEW_COMMENT        INCREMENT BY 1 START WITH 100 NOCACHE;
CREATE SEQUENCE SEQ_ADMIN                 INCREMENT BY 1 START WITH 100 NOCACHE;
CREATE SEQUENCE SEQ_ADMIN_RIGHTS          INCREMENT BY 1 START WITH 100 NOCACHE;
CREATE SEQUENCE SEQ_REPORT                INCREMENT BY 1 START WITH 100 NOCACHE;
CREATE SEQUENCE SEQ_REPORT_CATEGORY       INCREMENT BY 1 START WITH 100 NOCACHE;
CREATE SEQUENCE SEQ_QUESTION_ANSWER       INCREMENT BY 1 START WITH 100 NOCACHE;
CREATE SEQUENCE SEQ_NOTICE                INCREMENT BY 1 START WITH 100 NOCACHE;
CREATE SEQUENCE SEQ_NOTICE_CATEGORY       INCREMENT BY 1 START WITH 1   NOCACHE;
CREATE SEQUENCE SEQ_BANNER                INCREMENT BY 1 START WITH 100 NOCACHE;
CREATE SEQUENCE SEQ_FAQ                   INCREMENT BY 1 START WITH 1   NOCACHE;
CREATE SEQUENCE SEQ_FAQ_CATEGORY          INCREMENT BY 1 START WITH 1   NOCACHE;

CREATE SEQUENCE SEQ_ACCOUNT_DETAILS       INCREMENT BY 1 START WITH 100 NOCACHE;
CREATE SEQUENCE SEQ_ATTACHMENT            INCREMENT BY 1 START WITH 100 NOCACHE;

CREATE SEQUENCE SEQ_QUOTATION_NO            NOCACHE NOCYCLE;
CREATE SEQUENCE CASH_LOG_NO                 NOCACHE NOCYCLE;




--/제약조건 추가
--MEMBER
ALTER TABLE "MEMBER" 
ADD CONSTRAINT "PK_MEMBER" 
PRIMARY KEY (
"MEMBER_NO"
);
ALTER TABLE "MEMBER"  
ADD CONSTRAINT UNQ_MEMBER_NICK 
UNIQUE (
"MEMBER_NICK"
);

--FREE_BOARD
ALTER TABLE "FREE_BOARD" 
ADD CONSTRAINT "PK_FREE_BOARD" 
PRIMARY KEY (
    "BOARD_NO"
);
ALTER TABLE "FREE_BOARD" 
ADD CONSTRAINT "FK_MEMBER_NO" 
FOREIGN KEY (
    "MEMBER_NO"
)
REFERENCES "MEMBER" (
    "MEMBER_NO"
);

-- FREE_BOARD_COMMENT
ALTER TABLE "FREE_BOARD_COMMENT" 
ADD CONSTRAINT "PK_FREE_BOARD_COMMENT" 
PRIMARY KEY (
	"COMMENT_NO"
);
ALTER TABLE "FREE_BOARD_COMMENT" 
ADD CONSTRAINT "FK_MEMBER_NO_COMMENT" 
FOREIGN KEY (
    "MEMBER_NO"
)
REFERENCES "MEMBER" (
    "MEMBER_NO"
);
ALTER TABLE "FREE_BOARD_COMMENT" 
ADD CONSTRAINT "FK_BOARD_NO" 
FOREIGN KEY (
    "BOARD_NO"
)
REFERENCES "FREE_BOARD" (
    "BOARD_NO"
);


ALTER TABLE "FREE_BOARD_LIKE" 
ADD CONSTRAINT "FK_BOARD_NO_LIKE" 
FOREIGN KEY (
    "BOARD_NO"
)
REFERENCES "FREE_BOARD" (
    "BOARD_NO"
);

ALTER TABLE "FREE_BOARD_LIKE" 
ADD CONSTRAINT "FK_MEMBER_NO_LIKE" 
FOREIGN KEY (
    "MEMBER_NO"
)
REFERENCES "MEMBER" (
    "MEMBER_NO"
);


ALTER TABLE "QNA_CATEGORY" ADD CONSTRAINT "PK_QNA_CATEGORY" PRIMARY KEY (
	"QNA_CAT_NO"
);


ALTER TABLE "MESSAGE" ADD CONSTRAINT "PK_MESSAGE" PRIMARY KEY (
	"MAIL_NO"
);
ALTER TABLE "FREELANCER" ADD CONSTRAINT "PK_FREELANCER" PRIMARY KEY (
	"FREELANCER_NO"
);
ALTER TABLE "REQUEST" ADD CONSTRAINT "PK_REQUEST" PRIMARY KEY (
	"REQUEST_NO"
);


ALTER TABLE "ESTIMATE" ADD CONSTRAINT "PK_ESTIMATE" PRIMARY KEY (
	"ESTIMATE_NO"
);
ALTER TABLE "ESTIMATE_CAT" ADD CONSTRAINT "PK_ESTIMATE_CAT" PRIMARY KEY (
	"ESTIMATE_CAT_NO"
);

ALTER TABLE "ESTIMATE" 
ADD CONSTRAINT "FK_ESTIMATE_CAT_NO" 
FOREIGN KEY (
    "ESTIMATE_CAT_NO"
)
REFERENCES "ESTIMATE_CAT" (
    "ESTIMATE_CAT_NO"
);

ALTER TABLE "ESTIMATE" 
ADD CONSTRAINT "FK_ESTIMATE_FREELANCER_NO" 
FOREIGN KEY (
    "FREELANCER_NO"
)
REFERENCES "FREELANCER" (
    "FREELANCER_NO"
);

ALTER TABLE "FAQ" ADD CONSTRAINT "PK_FAQ" PRIMARY KEY (
	"FAQ_NO"
);
ALTER TABLE "ADMIN" ADD CONSTRAINT "PK_ADMIN" PRIMARY KEY (
	"ADMIN_NO"
);
ALTER TABLE "NOTICE" ADD CONSTRAINT "PK_NOTICE" PRIMARY KEY (
	"NOTI_NO"
);
ALTER TABLE "QNA" ADD CONSTRAINT "PK_QNA" PRIMARY KEY (
	"QNA_NO"
);
ALTER TABLE "REPORT" ADD CONSTRAINT "PK_REPORT" PRIMARY KEY (
	"RPT_NO"
);
ALTER TABLE "QUOTATION" ADD CONSTRAINT "PK_QUOTATION" PRIMARY KEY (
	"QUOTATION_NO"
);
ALTER TABLE "ESTIMATE_OPTION" ADD CONSTRAINT "PK_ESTIMATE_OPTION" PRIMARY KEY (
	"ESTIMATE_OPTION_NO"
);
ALTER TABLE "QUESTION_ANSWER" ADD CONSTRAINT "PK_QUESTION_ANSWER" PRIMARY KEY (
	"QUESTION_ANSWER_NO"
);
ALTER TABLE "REVIEW" ADD CONSTRAINT "PK_REVIEW" PRIMARY KEY (
	"REVIEW_NO"
);

ALTER TABLE "MEMBER_STATUS" ADD CONSTRAINT "PK_MEMBER_STATUS" PRIMARY KEY (
	"STATUS_NO"
);
ALTER TABLE "FAQ_CATEGORY" ADD CONSTRAINT "PK_FAQ_CATEGORY" PRIMARY KEY (
	"FAQ_CAT_NO"
);
ALTER TABLE "NOTICE_CATEGORY" ADD CONSTRAINT "PK_NOTICE_CATEGORY" PRIMARY KEY (
	"NOTI_CAT_NO"
);
ALTER TABLE "REPORT_CATEGORY" ADD CONSTRAINT "PK_REPORT_CATEGORY" PRIMARY KEY (
	"RPT_CAT_NO"
);
ALTER TABLE "REQUEST_CAT" ADD CONSTRAINT "PK_REQUEST_CAT" PRIMARY KEY (
	"REQUEST_CAT_NO"
);
ALTER TABLE "FREELANCER_CLASS" ADD CONSTRAINT "PK_FREELANCER_CLASS" PRIMARY KEY (
	"FREELANCER_CLASS_NO"
);
ALTER TABLE "WISH_LIST" ADD CONSTRAINT "PK_WISH_LIST" PRIMARY KEY (
	"MEMBER_NO",
	"ESTIMATE_NO"
);
ALTER TABLE "RECEIPT" ADD CONSTRAINT "PK_RECEIPT" PRIMARY KEY (
	"RECEIPT_NO"
);
ALTER TABLE "ACCOUNT" ADD CONSTRAINT "PK_ACCOUNT" PRIMARY KEY (
	"TRANSACTION_ID"
);
ALTER TABLE "DEPOSIT_DETAIL" ADD CONSTRAINT "PK_DEPOSIT_DETAIL" PRIMARY KEY (
	"DEPOSIT_NO"
);
ALTER TABLE "WITHDRAWAL_DETAIL" ADD CONSTRAINT "PK_WITHDRAWAL_DETAIL" PRIMARY KEY (
	"WITHDRWAL_ID"
);
ALTER TABLE "FREELANCER_QA" ADD CONSTRAINT "PK_FREELANCER_QA" PRIMARY KEY (
	"F_QNA_NO"
);
ALTER TABLE "FREELACNER_QA_REPLY" ADD CONSTRAINT "PK_FREELACNER_QA_REPLY" PRIMARY KEY (
	"F_QNA_REPLY_NO"
);
ALTER TABLE "REVIEW_COMMENT" ADD CONSTRAINT "PK_REVIEW_COMMENT" PRIMARY KEY (
	"REVIEW_COMMENT_NO"
);

ALTER TABLE "ADMIN_RIGHTS" ADD CONSTRAINT "PK_ADMIN_RIGHTS" PRIMARY KEY (
	"ADMIN_RIGHTS_NO"
);
ALTER TABLE "BANNER" ADD CONSTRAINT "PK_BANNER" PRIMARY KEY (
	"BANNER_NO"
);
ALTER TABLE "ALERT" ADD CONSTRAINT "PK_ALERT" PRIMARY KEY (
	"ALERT_NO"
);
ALTER TABLE "QUOTATION_STATUS" ADD CONSTRAINT "PK_QUOTATION_STATUS" PRIMARY KEY (
	"QUOTATION_STATUS_NO"
);
ALTER TABLE "ALERT_CAT" ADD CONSTRAINT "PK_ALERT_CAT" PRIMARY KEY (
	"ALERT_CAT_NO"
);
ALTER TABLE "ACCOUNT_DETAILS" ADD CONSTRAINT "PK_ACCOUNT_DETAILS" PRIMARY KEY (
	"Key"
);
ALTER TABLE "CAREER" ADD CONSTRAINT "PK_CAREER" PRIMARY KEY (
	"CAREER_NO"
);
ALTER TABLE "EDUCATION" ADD CONSTRAINT "PK_EDUCATION" PRIMARY KEY (
	"EDU_NO"
);


ALTER TABLE "FREE_BOARD_LIKE" ADD CONSTRAINT "PK_FREE_BOARD_LIKE" PRIMARY KEY (
	"LIKE_NO"
);

-- 첨부파일(커뮤니티) 제약조건 
ALTER TABLE "ATTACHMENT"
ADD CONSTRAINT "PK_ATTACHMENT" PRIMARY KEY ("ATTACHMENT_NO");

ALTER TABLE "ATTACHMENT"
ADD CONSTRAINT "FK_ESTIMATE_TO_ATTACHMENT"
FOREIGN KEY ("ESTIMATE_NO") REFERENCES "ESTIMATE" ("ESTIMATE_NO");


-- 프리보드 카테고리 테이블 기본키 추가

ALTER TABLE FREE_BOARD_CATEGORY
ADD CONSTRAINT PK_FREE_BOARD_CATEGORY PRIMARY KEY (FREE_BOARD_CATEGORY_NO);

 ALTER TABLE ESTIMATE_FAQ
ADD CONSTRAINT FK_ESTIMATE_NO
FOREIGN KEY (ESTIMATE_NO)
REFERENCES ESTIMATE (ESTIMATE_NO);

--/더미데이터
-- MEMBER 
DECLARE
  v_start_date DATE := TRUNC(SYSDATE, 'YYYY') + INTERVAL '1' MONTH;
  v_end_date DATE := SYSDATE;
  v_member_sign_date DATE;
  v_member_modifi_date DATE;
  v_status_no NUMBER;
  v_prev_sign_date DATE := v_start_date;
BEGIN
  FOR i IN 1..200 LOOP
    v_member_sign_date := v_prev_sign_date + DBMS_RANDOM.VALUE * (v_end_date - v_prev_sign_date);
    v_member_modifi_date := v_member_sign_date + DBMS_RANDOM.VALUE * (v_end_date - v_member_sign_date);
    
    IF i >= 16 AND i <= 19 THEN
      v_status_no := 3;
    ELSIF i = 20 THEN
      v_status_no := 4;
    ELSE
      v_status_no := 1;
    END IF;
  
    INSERT INTO MEMBER (
      MEMBER_NO,
      STATUS_NO,
      MEMBER_ID,
      MEMBER_PWD,
      MEMBER_NICK,
      MEMBER_NAME,
      MEMBER_PHONE,
      MEMBER_EMAIL,
      MEMBER_INTERST,
      MEMBER_BANK,
      MEMBER_ACCOUNT,
      MEMBER_CASH,
      MEMBER_ADDRESS,
      MEMBER_SIGN_DATE,
      MEMBER_MODIFI_DATE
    )
    VALUES (
      SEQ_MEMBER.NEXTVAL,
      v_status_no,
      'user' || LPAD(i, 3, '0'),
      '1234',
      'nick' || LPAD(i, 3, '0'),
      '이름' || LPAD(i, 3, '0'),
      '010'|| RPAD(i, 8, '0'),
      'user' || LPAD(i, 3, '0') || '@email.com',
      LPAD(i, 3, '0'),
      '은행' || LPAD(i, 3, '0'),
      '계좌' || LPAD(i, 3, '0'),
      i || 00,
      '주소' || LPAD(i, 3, '0'),
      v_member_sign_date,
      v_member_modifi_date
    );
    
    v_prev_sign_date := v_member_sign_date; -- 이전 레코드의 MEMBER_SIGN_DATE 값을 갱신
  END LOOP;
END;
/





-- MEMBER_STATUS 
INSERT INTO MEMBER_STATUS (STATUS_NO,STATUS_NAME) VALUES (SEQ_MEMBER_STATUS.NEXTVAL, '보통' );
INSERT INTO MEMBER_STATUS (STATUS_NO,STATUS_NAME) VALUES (SEQ_MEMBER_STATUS.NEXTVAL, '전문가' );
INSERT INTO MEMBER_STATUS (STATUS_NO,STATUS_NAME) VALUES (SEQ_MEMBER_STATUS.NEXTVAL, '정지' );
INSERT INTO MEMBER_STATUS (STATUS_NO,STATUS_NAME) VALUES (SEQ_MEMBER_STATUS.NEXTVAL, '탈퇴' );


-- FREE_BOARD
BEGIN 
  FOR i IN 1..10 LOOP
    INSERT INTO FREE_BOARD (
      BOARD_NO,
      MEMBER_NO,
      FREE_BOARD_TITLE,
      FREE_BOARD_CONTENT,
      FREE_BOARD_ENROLL_DATE,
      FREE_BOARD_EDIT_DATE,
      FREE_BOARD_HIT,
      FREE_BOARD_LIKE
    )
    VALUES (
      SEQ_FREE_BOARD.NEXTVAL,
      SEQ_FREE_BOARD.NEXTVAL,
      '제목' || LPAD(i, 3, '0'),
      LPAD(i, 3, '0') || '번째 자유게시판 내용입니다',
      SYSDATE,
      SYSDATE,
      i,
      i
    );
  END LOOP;
END;
/

--FREE_BOARD_COMMENT
BEGIN
    FOR i IN 1..10 LOOP
    INSERT INTO FREE_BOARD_COMMENT (
        COMMENT_NO,
        MEMBER_NO,
        BOARD_NO,
        REPLY_NO,
        COMMENT_CONTENT,
        COMMENT_ENROLL_DATE,
        COMMENT_EDIT_DATE
    )
    VALUES (
        SEQ_FREE_BOARD_COMMENT.NEXTVAL,
        SEQ_FREE_BOARD_COMMENT.NEXTVAL,
        SEQ_FREE_BOARD_COMMENT.NEXTVAL,
        SEQ_FREE_BOARD_COMMENT.NEXTVAL,
        '댓글 내용' || LPAD(i, 3, '0'),
        SYSDATE,
        SYSDATE
    );
    END LOOP;
END;
/

-- 카테고리 분류 : 대 1, 중 2, 소 3

-- ESTIMATE_CAT
INSERT INTO ESTIMATE_CAT 
( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
VALUES (1, 0, 'IT/프로그래밍' , 1, 'Cat_Coding.svg');

    INSERT INTO ESTIMATE_CAT 
    ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
    VALUES (101, 1, 'UX 기획' , 2, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (10101, 101, '웹•모바일앱 기획' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (10102, 101, '기타 기획' , 3, NULL);
    
    INSERT INTO ESTIMATE_CAT 
    ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
    VALUES (102, 1, '웹' , 2, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (10201, 102, '홈페이지' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (10202, 102, '랜딩페이지' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (10203, 102, '프론트엔드•퍼블리싱' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (10204, 102, '검색최적화•SEO' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (10205, 102, '애널리틱스' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (10206, 102, '홈페이지 수정•유지보수' , 3, NULL);
    
    INSERT INTO ESTIMATE_CAT 
    ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
    VALUES (103, 1, '커머스' , 2, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (10301, 103, '쇼핑몰' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (10302, 103, '쇼핑몰 수정•유지보수' , 3, NULL);
    
    INSERT INTO ESTIMATE_CAT 
    ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
    VALUES (104, 1, '모바일' , 2, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (10401, 104, '앱' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (10402, 104, '앱 수정•유지보수' , 3, NULL);
    
    INSERT INTO ESTIMATE_CAT 
    ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
    VALUES (105, 1, '프로그램' , 2, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (10501, 105, '비지니스 애플리케이션' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (10502, 105, 'PC•웹 프로그램' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (10503, 105, '백엔드•서버' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (10504, 105, '봇•챗봇' , 3, NULL);
    
    INSERT INTO ESTIMATE_CAT 
    ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
    VALUES (106, 1, '트렌드' , 2, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (10601, 106, 'AI 애플리케이션' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (10602, 106, '게임•AR•VR' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (10603, 106, '노코드•로우코드' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (10604, 106, '메타버스' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (10605, 106, '블록체인•NFT' , 3, NULL);
        
    INSERT INTO ESTIMATE_CAT 
    ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
    VALUES (107, 1, '데이터' , 2, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (10701, 107, '데이터 구매•구축' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (10702, 107, '데이터 마이닝•크롤링' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (10703, 107, '데이터 전처리' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (10704, 107, '데이터 라벨링' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (10705, 107, '데이터 분석•시각화' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (10706, 107, '인공지능•머신러닝' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (10707, 107, '데이터베이스' , 3, NULL);
    
    INSERT INTO ESTIMATE_CAT 
    ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
    VALUES (108, 1, '기타' , 2, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (10801, 108, '하드웨어•임베디드' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (10802, 108, '보안' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (10803, 108, 'QA•테스트' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (10804, 108, '컴퓨터 기술지원' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (10805, 108, '파일변환' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (10806, 108, '기타' , 3, NULL);
        
    
    INSERT INTO ESTIMATE_CAT 
    ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
    VALUES (109, 1, '직무직군' , 2, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (10901, 109, '백엔드 개발자' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (10902, 109, '풀스택 개발자' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (10903, 109, 'DevOps 엔지니어' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (10904, 109, '데이터 직군' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (10905, 109, 'ML•DL 직군' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (10906, 109, '인프라 직군' , 3, NULL);


INSERT INTO ESTIMATE_CAT 
( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
VALUES (2, 0, '디자인' , 1, 'Cat_Design.svg');

    INSERT INTO ESTIMATE_CAT 
    ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
    VALUES (201, 2, '로고•브랜딩' , 2, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (20101, 201, '로고 디자인' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (20102, 201, '브랜드 디자인•가이드' , 3, NULL);
    
    INSERT INTO ESTIMATE_CAT 
    ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
    VALUES (202, 2, '웹•모바일 디자인' , 2, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (20201, 202, '웹 디자인' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (20202, 202, '앱•모바일 디자인' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (20203, 202, '템플릿형 홈페이지' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (20204, 202, '아이콘•버튼' , 3, NULL);
    
    INSERT INTO ESTIMATE_CAT 
    ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
    VALUES (203, 2, '캐릭터•일러스트' , 2, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (20301, 203, '일러스트' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (20302, 203, '캐리커쳐' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (20303, 203, '웹툰•콘티' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (20304, 203, '캐릭터' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (20305, 203, '이모티콘' , 3, NULL);
    
    INSERT INTO ESTIMATE_CAT 
    ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
    VALUES (204, 2, '공간•건축' , 2, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (20401, 204, '도면제작•수정' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (20402, 204, '인테리어 컨설팅' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (20403, 204, '전시•무대 디자인' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (20404, 204, '간판•시공' , 3, NULL);
    
    INSERT INTO ESTIMATE_CAT 
    ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
    VALUES (205, 2, '인쇄•홍보물' , 2, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (20501, 205, '명함' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (20502, 205, '전단지•포스터•인쇄물' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (20503, 205, '현수막•X배너' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (20504, 205, '메뉴판' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (20505, 205, '홍보물 인쇄•출력' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (20506, 205, '스티커•봉투•초대장' , 3, NULL);
    
    INSERT INTO ESTIMATE_CAT 
    ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
    VALUES (206, 2, '패키지•커버' , 2, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (20601, 206, '패키지' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (20602, 206, '책표지•내지' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (20603, 206, '전자책 표지•내지' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (20604, 206, '앨범커버' , 3, NULL);
    
    INSERT INTO ESTIMATE_CAT 
    ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
    VALUES (207, 2, '게임•웹3.0' , 2, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (20701, 207, 'AI 디자인' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (20702, 207, 'VR•AR 게임' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (20703, 207, '메타버스' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (20704, 207, 'NFT아트' , 3, NULL);
        
    
    INSERT INTO ESTIMATE_CAT 
    ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
    VALUES (208, 2, '패션•택스타일' , 2, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (20801, 208, '의류•주얼리 디자인' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (20802, 208, '작업지시서•도식화' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (20803, 208, '패턴•샘플제작' , 3, NULL);
    
    INSERT INTO ESTIMATE_CAT 
    ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
    VALUES (209, 2, '캘리그라피•폰트' , 2, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (20901, 209, '캘리그라피' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (20902, 209, '폰트' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (20903, 209, '사인•직인' , 3, NULL);
    
    INSERT INTO ESTIMATE_CAT 
    ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
    VALUES (210, 2, '산업•제품 디자인' , 2, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (21001, 210, '제품 모델링•랜더링' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (21002, 210, '제품•기구 설계' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (21003, 210, '제품 도면•스케치' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (21004, 210, '시제품•3D프린팅' , 3, NULL);
    
    INSERT INTO ESTIMATE_CAT 
    ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
    VALUES (211, 2, '마케팅 디자인' , 2, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (21101, 211, '상세페이지' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (21102, 211, '블로그•카페 디자인' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (21103, 211, 'SNS•썸네일 디자인' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (21104, 211, '배너•배달어플' , 3, NULL);
    
    INSERT INTO ESTIMATE_CAT 
    ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
    VALUES (212, 2, '그래픽 디자인' , 2, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (21201, 212, 'PPT•인포그래픽' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (21202, 212, '포토샵•파일변환' , 3, NULL);
    
    INSERT INTO ESTIMATE_CAT 
    ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
    VALUES (213, 2, '기타' , 2, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (21301, 213, '디자인 템플릿형' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (21302, 213, '바코드•QR 코드' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (21303, 213, '기타' , 3, NULL);
        

INSERT INTO ESTIMATE_CAT 
( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
VALUES (3, 0, '마켓팅' , 1, 'Cat_Markerting.svg');
    
    INSERT INTO ESTIMATE_CAT 
    ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
    VALUES (301, 3, '채널 활성화' , 2, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (30101, 301, '블로그 관리' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (30102, 301, '카페 관리' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (30103, 301, '인스타그램 관리' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (30104, 301, '유튜브 관리' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (30105, 301, '기타 채널 관리' , 3, NULL);
    
    INSERT INTO ESTIMATE_CAT 
    ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
    VALUES (302, 3, '바이럴•체험단' , 2, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (30201, 302, '체험단•기자단' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (30202, 302, '개인 인플루언서' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (30203, 302, '바이럴•포스팅' , 3, NULL);
    
    INSERT INTO ESTIMATE_CAT 
    ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
    VALUES (303, 3, 'PR•행사' , 2, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (30301, 303, '언론홍보' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (30302, 303, '행사•이벤트' , 3, NULL);
    
    INSERT INTO ESTIMATE_CAT 
    ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
    VALUES (304, 3, '업종•목적별' , 2, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (30401, 304, '종합광고대행' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (30402, 304, '스토어 마케팅' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (30403, 304, '업종별 마케팅 패키지' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (30404, 304, 'CPA 마케팅' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (30405, 304, '라이브커머스' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (30406, 304, '메시지 마케팅' , 3, NULL);
    
    INSERT INTO ESTIMATE_CAT 
    ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
    VALUES (305, 3, '최적화 노출' , 2, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (30501, 305, 'SEO•최적화 노출' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (30502, 305, '웹 트래픽' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (30503, 305, '지도 마케팅' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (30504, 305, '앱 마케팅' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (30505, 305, '포털 질문•답변' , 3, NULL);
    
    INSERT INTO ESTIMATE_CAT 
    ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
    VALUES (306, 3, '해외 마케팅' , 2, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (30601, 306, '해외 언론홍보' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (30602, 306, '해외 검색•쇼핑몰' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (30603, 306, '해외 SNS•바이럴' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (30604, 306, '기타 해외 마케팅' , 3, NULL);
    
    INSERT INTO ESTIMATE_CAT 
    ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
    VALUES (307, 3, '광고(퍼포먼스)' , 2, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (30701, 307, 'SNS 광고' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (30702, 307, '키워드•검색 광고' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (30703, 307, '디스플레이•영상•배너' , 3, NULL);
    
    INSERT INTO ESTIMATE_CAT 
    ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
    VALUES (308, 3, '분석•전략' , 2, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (30801, 308, '마케팅 컨설팅' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (30802, 308, '브랜드 컨설팅' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (30803, 308, '데이터 성과 분석' , 3, NULL);
    
    INSERT INTO ESTIMATE_CAT 
    ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
    VALUES (309, 3, 'AI 마케팅' , 2, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (30901, 309, 'AI 마케팅 콘텐츠' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (30902, 309, 'AI 컨설팅 기타' , 3, NULL);
    
    INSERT INTO ESTIMATE_CAT 
    ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
    VALUES (310, 3, '옥외•인쇄•방송 광고' , 2, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (31001, 310, '버스•지하철•택시' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (31002, 310, '전광판•키오크스' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (31003, 310, 'TV•라디오' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (31004, 310, '인쇄 광고' , 3, NULL);
    
    INSERT INTO ESTIMATE_CAT 
    ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
    VALUES (311, 3, '기타 마케팅' , 2, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (31101, 311, '커뮤니티•사이트 배너' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (31102, 311, '영상 광고' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (31103, 311, '마케팅 자료•키워드' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (31104, 311, '기타' , 3, NULL);


INSERT INTO ESTIMATE_CAT 
( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
VALUES (4, 0, '영상/음향' , 1, 'Cat_Sound.svg');

    INSERT INTO ESTIMATE_CAT 
    ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
    VALUES (401, 4, '영상' , 2, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (40101, 401, '광고•홍보 영상' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (40102, 401, '제품 영상' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (40103, 401, '교육 영상' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (40104, 401, '행사 영상' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (40105, 401, '유튜브 영상' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (40106, 401, '온라인 중계' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (40107, 401, '드론 촬영' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (40108, 401, '컴퓨터 그래픽' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (40109, 401, '애니메이션' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (40110, 401, '영상 후반작업' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (40111, 401, '영상 기타' , 3, NULL);
    
    INSERT INTO ESTIMATE_CAT 
    ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
    VALUES (402, 4, '음향' , 2, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (40201, 402, '성우' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (40202, 402, '음악•음원' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (40203, 402, '오디오 컨텐츠' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (40204, 402, '오디오 엔지니어링' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (40205, 402, '기타 음향•음악' , 3, NULL);
    
    INSERT INTO ESTIMATE_CAT 
    ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
    VALUES (403, 4, '사진' , 2, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (40301, 403, '제품•홍보 사진' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (40302, 403, '개인•이벤트 사진' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (40303, 403, '사진 보정' , 3, NULL);
    
    INSERT INTO ESTIMATE_CAT 
    ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
    VALUES (404, 4, 'AI 콘텐츠' , 2, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (40401, 404, 'AI 영상•사진•음향' , 3, NULL);
    
    INSERT INTO ESTIMATE_CAT 
    ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
    VALUES (405, 4, '엔터테이너' , 2, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (40501, 405, '모델•배우' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (40502, 405, '쇼호스트' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (40503, 405, 'MC' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (40504, 405, '공연' , 3, NULL);
    
    INSERT INTO ESTIMATE_CAT 
    ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
    VALUES (406, 4, '기타' , 2, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (40601, 406, '콘티•스토리보드' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (40602, 406, '헤어메이크업' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (40603, 406, '스튜디오 렌탈' , 3, NULL);
        INSERT INTO ESTIMATE_CAT 
        ( ESTIMATE_CAT_NO,ABOVE_CAT_NO,ESTIMATE_CAT_NAME,ESTIMATE_CAT_SCOPE,ESTIMATE_CAT_FILE ) 
        VALUES (40604, 406, '기타' , 3, NULL);
    



    
-- USER_CASH 
--BEGIN 
--  FOR i IN 1..10 LOOP
--    INSERT INTO USER_CASH (
--        CASH_NO,
--        MEMBER_NO,
--        CASH_POINT,
--        CASH_MONEY,
--        CASH_ENORLLDATE
--    )
--    VALUES (
--        SEQ_USER_CASH.NEXTVAL,
--        i,
--        i || 000,
--        i || 000,
--        SYSDATE
--    );
--  END LOOP;
--END;
--/

-- WISH_LIST 
BEGIN 
  FOR i IN 1..10 LOOP
    INSERT INTO WISH_LIST (
        MEMBER_NO,
        ESTIMATE_NO
    )
    VALUES (
        SEQ_MEMBER_STATUS.NEXTVAL,
        SEQ_MEMBER_STATUS.NEXTVAL
    );
  END LOOP;
END;
/

-- QNA
BEGIN 
  FOR i IN 1..10 LOOP
    INSERT INTO QNA (
        QNA_NO,
        MEMBER_NO,
        QNA_CAT_NO,
        QNA_TITLE,
        QNA_CONTENT,
        QNA_ENROLLDATE,
        QNA_STATUS
    )
    VALUES (
        SEQ_QNA.NEXTVAL,
        SEQ_QNA.NEXTVAL,
        SEQ_QNA.NEXTVAL,
        'QNA 제목' || LPAD(i, 3 , '0'),
        'QNA 내용' || LPAD(i, 3 , '0'),
        SYSDATE,
        'N'
    );
  END LOOP;
END;
/

-- QNA_CATEGORY
BEGIN
    FOR i IN 1..10 LOOP
    INSERT INTO QNA_CATEGORY (
        QNA_CAT_NO,
        QNA_CAT_NAME	    
    )
    VALUES (
        SEQ_QNA_CATEGORY.NEXTVAL,
        '카테고리' || LPAD(i , 3, '0')
    );
    END LOOP;
END;
/

-- FREELANCER
BEGIN
  FOR i IN 1..10 LOOP
    INSERT INTO FREELANCER (
      FREELANCER_NO,
      MEMBER_NO,
      FREELANCER_CLASS_NO,
      FREELANCER_INRODUCTION,
      FIELD_OF_EXPERTISE,
     
      FREELANCER_CONTACT_TIME,
      FREELANCER_STATUS
    )
    VALUES (
      SEQ_FREELANCER.NEXTVAL,
      SEQ_FREELANCER.NEXTVAL,
      i,
      '소개' || LPAD(i , 3 , '0'),
      '전문분야' || LPAD(i , 3 , '0'),
      
      LPAD(i , 2 , '0') || ':00',
      'Y'
    );
  END LOOP;
END;
/

-- FREELANCER_CLASS
INSERT INTO FREELANCER_CLASS( FREELANCER_CLASS_NO , FREELANCER_CLASS_NAME ) VALUES ( SEQ_FREELANCER_CLASS.NEXTVAL, '스킬 레벨 0');
INSERT INTO FREELANCER_CLASS( FREELANCER_CLASS_NO , FREELANCER_CLASS_NAME ) VALUES ( SEQ_FREELANCER_CLASS.NEXTVAL, '스킬 레벨 1');
INSERT INTO FREELANCER_CLASS( FREELANCER_CLASS_NO , FREELANCER_CLASS_NAME ) VALUES ( SEQ_FREELANCER_CLASS.NEXTVAL, '스킬 레벨 2');
INSERT INTO FREELANCER_CLASS( FREELANCER_CLASS_NO , FREELANCER_CLASS_NAME ) VALUES ( SEQ_FREELANCER_CLASS.NEXTVAL, '스킬 레벨 3');

-- CAREER
BEGIN 
  FOR i IN 1..10 LOOP
    INSERT INTO CAREER (
        CAREER_NO,
        FREELANCER_NO,
        CAREER_DATE,
        CAREER_COMPANY,
        CAREER_DEPT,
        CAREER_RESP,
        CAREER_LOCATION,
        CAREER_EMP_DATE
    )
    VALUES (
        SEQ_CAREER.NEXTVAL,
        SEQ_CAREER.NEXTVAL,
        i || 00,
        '회사' || LPAD(i , 3 , '0'),
        '부서' || LPAD(i , 3 , '0'),
        '직위' || LPAD(i , 3 , '0'),
        '근무지역' || LPAD(i , 3 , '0'),
        i || 00
    );
  END LOOP;
END;
/

-- MESSAGE
BEGIN
  FOR i IN 1..10 LOOP
    INSERT INTO MESSAGE (
      MAIL_NO,
      QUOTATION_NO,
      MEMBER_NO2,
      REQUEST_NO,
      MAIL_TITLE,
      MAIL_CONTENT,
      MAIL_FILE,
      MAIL_ENROLL_DATE,
      MAIL_CHECK,
      MAIL_STATUS
    )
    VALUES (
      SEQ_MESSAGE.NEXTVAL,
      i,
      i,
      i,
      '제목' || LPAD(i, 3, '0'),
      LPAD(i, 3, '0') || '번째 메세지 내용',
      '파일' || LPAD(i, 3, '0') || '.pdf',
      SYSDATE,
      '0',
      '1'
    );
  END LOOP;
END;
/




-- REQUEST
BEGIN 
  FOR i IN 1..10 LOOP
    INSERT INTO REQUEST (
            REQUEST_NO,
            REQUEST_CAT_NO,
            QUOTATION_NO,
            REQUEST_CONSENT,
            REQUEST_PRICE,
            REQUEST_PERIOD
    )
    VALUES (
      SEQ_REQUEST.NEXTVAL,
      i,
      i,
      0,
      i||000,
      i||'일'
    );
  END LOOP;
END;
/




-- ESTIMATE
--BEGIN 
--  FOR i IN 1..10 LOOP
--    INSERT INTO ESTIMATE (
--            ESTIMATE_NO,
--            FREELANCER_NO,
--            ESTIMATE_CAT_NO,
--            ESTIMATE_TITLE,
--            ESTIMATE_THUMBNAIL,
--            ESTIMATE_LINE_INTRODUCTION,
--            ESTIMATE_PRICE,
--            ESTIMATE_DETAIL,
--            ESTIMATE_DETAIL_FILE,
--            ESTIMATE_PORTFOLIO,
--            BUSINESS_REGISTRATION_NUMBER,
--            ESTIMATE_ENROLL_DATE,
--            ESTIMATE_MODIFICATION_DATE,
--            ESTIMATE_STATUS,
--            ESTIMATE_VIEWS
--    )
--    VALUES (
--      SEQ_ESTIMATE.NEXTVAL,
--      SEQ_ESTIMATE.NEXTVAL,
--      SEQ_ESTIMATE.NEXTVAL,
--      '견적서 제목' || LPAD(i , 3 , '0'),
--      '썸네일(첨부파일)'|| LPAD(i , 3 , '0') || '.jpg',
--      '한줄 소개' || LPAD(i , 3 , '0'),
--      i || '0000',
--      '상세내용' || LPAD(i , 3 , '0'),
--      '상세내용(첨부파일)' || LPAD(i , 3 , '0') || '.jpg',
--      '포폴' || LPAD(i , 3 , '0'),
--      LPAD(i , 3 , '0'),
--      SYSDATE,
--      SYSDATE,
--      'Y',
--      i
--    );
--  END LOOP;
--END;
--/





-- ADMIN 
BEGIN 
  FOR i IN 1..10 LOOP
    INSERT INTO ADMIN (
        ADMIN_NO,
        ADMIN_GR_NO,
        ADMIN_ID,
        ADMIN_PWD,
        ADMIN_NICK
    )
    VALUES (
        SEQ_ADMIN.NEXTVAL,
        i,
        'ADMIN' || LPAD(i , 3 , '0'),
        '1234',
        'ADMIN' || LPAD(i , 3 , '0')
    );
  END LOOP;
END;
/

--REPORT
BEGIN 
  FOR i IN 1..10 LOOP
    INSERT INTO REPORT (
        RPT_NO,
        RPTCAT_NO,
        MEMBER_NO,
        MEMBER_NO_BAD,
        RPT_TITLE,
        RPT_CONTENT
    )
    VALUES (
        SEQ_REPORT.NEXTVAL,
        i,
        i,
        i+10,
        '신고 제목' || LPAD(i , 3 , '0'),
        '신고 내용'|| LPAD(i , 3 , '0')
    );
  END LOOP;
END;
/


-- FAQ 
BEGIN
  FOR i IN 1..10 LOOP
    INSERT INTO FAQ (
        FAQ_NO,
        ADMIN_NO,
        FAQ_CAT_NO,
        FAQ_TITLE,
        FAQ_Q_CONTENT,
        FAQ_A_CONTENT,
        FAQ_STATUS,
        FAQ_HIT,
        FAQ_ENROLLDATE,
        FAQ_MODIFYDATE
    )
    VALUES (
        SEQ_FAQ.NEXTVAL,
        i,
        LEAST(i, 6), -- FAQ_CAT_NO 값은 최대 6으로 설정
        'FAQ 제목' || LPAD(i , 3 , '0'),
        '질문 내용'|| LPAD(i , 3 , '0') || '.jpg',
        '답변 내용' || LPAD(i , 3 , '0'),
        'Y',
        i,
        SYSDATE,
        SYSDATE
    );
  END LOOP;
END;
/


-- FAQ_CAT
INSERT INTO FAQ_CATEGORY ( FAQ_CAT_NO, FAQ_CAT_NAME ) VALUES ( SEQ_FAQ_CATEGORY.NEXTVAL , '서비스 소개' );
INSERT INTO FAQ_CATEGORY ( FAQ_CAT_NO, FAQ_CAT_NAME ) VALUES ( SEQ_FAQ_CATEGORY.NEXTVAL , '이용방법' );
INSERT INTO FAQ_CATEGORY ( FAQ_CAT_NO, FAQ_CAT_NAME ) VALUES ( SEQ_FAQ_CATEGORY.NEXTVAL , '구매/환불' );
INSERT INTO FAQ_CATEGORY ( FAQ_CAT_NO, FAQ_CAT_NAME ) VALUES ( SEQ_FAQ_CATEGORY.NEXTVAL , '계정' );
INSERT INTO FAQ_CATEGORY ( FAQ_CAT_NO, FAQ_CAT_NAME ) VALUES ( SEQ_FAQ_CATEGORY.NEXTVAL , '신고/제보' );
INSERT INTO FAQ_CATEGORY ( FAQ_CAT_NO, FAQ_CAT_NAME ) VALUES ( SEQ_FAQ_CATEGORY.NEXTVAL , '문제해결' );



-- NOTICE 
BEGIN 
  FOR i IN 1..10 LOOP
    INSERT INTO NOTICE (
        NOTI_NO, 
        NOTI_CAT_NO, 
        ADMIN_NO, 
        NOTI_TITLE, 
        NOTI_CONTENT, 
        NOTI_ENROLLDATE, 
        NOTI_MODIFYDATE, 
        NOTI_STATUS, 
        NOTI_HIT
    )
    VALUES (
        SEQ_NOTICE.NEXTVAL,
        '1',
        SEQ_NOTICE.NEXTVAL,
        '공지 제목' || LPAD(i , 3 , '0'),
        '공지 내용'|| LPAD(i , 3 , '0') || '.jpg',
        SYSDATE,
        SYSDATE,
        'Y',
        i        
    );
  END LOOP;
END;
/

INSERT INTO NOTICE_CATEGORY ( NOTI_CAT_NO , NOTI_CAT_NAME ) VALUES ( SEQ_NOTICE_CATEGORY.NEXTVAL , '공지');
INSERT INTO NOTICE_CATEGORY ( NOTI_CAT_NO , NOTI_CAT_NAME ) VALUES ( SEQ_NOTICE_CATEGORY.NEXTVAL , '이벤트');
INSERT INTO NOTICE_CATEGORY ( NOTI_CAT_NO , NOTI_CAT_NAME ) VALUES ( SEQ_NOTICE_CATEGORY.NEXTVAL , '안내');


-- 매출 기록
CREATE TABLE SALES_LOG (
    NO                  NUMBER      PRIMARY KEY,
    CATEGORY_NO         NUMBER      NOT NULL,
    SALES               NUMBER      NOT NULL,
    ENROLL_DATE         TIMESTAMP   DEFAULT SYSDATE,
    QUOTATION_NO        NUMBER
);


-- 매출원 종류
CREATE TABLE SALES_CATEGORY (
    NO                  NUMBER          PRIMARY KEY,
    CATEGORY_NAME      VARCHAR2(30)    NOT NULL,
    COMMITION           NUMBER          NOT NULL
);

--/FUNCTION

-- CAREER
CREATE OR REPLACE FUNCTION GET_CAREER_SEQ
    RETURN NUMBER
IS
    TEMP NUMBER;
BEGIN
    TEMP := SEQ_CAREER.NEXTVAL;
    RETURN TEMP;
    END;
/

-- EDUCATION
CREATE OR REPLACE FUNCTION GET_EDUCATION_SEQ
    RETURN NUMBER
IS
    TEMP NUMBER;
BEGIN
    TEMP := SEQ_EDUCATION.NEXTVAL;
    RETURN TEMP;
    END;
/




-- 결제방법
CREATE TABLE PAYMENT_METHOD (
    NO                      NUMBER          PRIMARY KEY,
    PAYMENT_METHOD_NAME     VARCHAR(30)     NOT NULL
);

-- 충전 환불 기록
CREATE TABLE CASH_LOG (
    NO                      NUMBER          PRIMARY KEY,
    MEMBER_NO               NUMBER          NOT NULL,
   LOG_CATEGORY_NO          NUMBER      NOT NULL,
    AMOUNT                  NUMBER          NOT NULL,
    PAYMENT_METHOD_NO       NUMBER,
    ENROLL_DATE             TIMESTAMP       DEFAULT SYSDATE
);
CREATE SEQUENCE SEQ_CASH_LOG_NO NOCACHE NOCYCLE;

-- 충전 OR 환불
CREATE TABLE LOG_CATEGORY (
   CATEGORY_NO NUMBER PRIMARY KEY,
   CATEGORY_NAME VARCHAR2(30)
);

-- 유저 보유 캐시,포인트
CREATE TABLE USER_CASH (
    MEMBER_NO           NUMBER                  NOT NULL,
    CASH_MONEY          NUMBER      DEFAULT 0   NOT NULL,
    CASH_POINT          NUMBER      DEFAULT 0   NOT NULL
);

-- 결제 방법
INSERT INTO PAYMENT_METHOD (NO, PAYMENT_METHOD_NAME) VALUES ( 1, '신용카드' );
INSERT INTO PAYMENT_METHOD (NO, PAYMENT_METHOD_NAME) VALUES ( 2, '계좌이체' );
INSERT INTO PAYMENT_METHOD (NO, PAYMENT_METHOD_NAME) VALUES ( 3, '휴대폰 결제' );
INSERT INTO PAYMENT_METHOD (NO, PAYMENT_METHOD_NAME) VALUES ( 4, '캐시 결제' );


INSERT INTO LOG_CATEGORY VALUES ( 1, '충전');
INSERT INTO LOG_CATEGORY VALUES ( 2, '환불');
INSERT INTO LOG_CATEGORY VALUES ( 3, '거래완료');
INSERT INTO LOG_CATEGORY VALUES ( 4, '구매');

-- CASH_LOG
--INSERT INTO CASH_LOG(NO, MEMBER_NO, LOG_CATEGORY_NO, AMOUNT,PAYMENT_METHOD_NO) VALUES (1, 120, 1, 1000, 1);
--INSERT INTO CASH_LOG(NO, MEMBER_NO, LOG_CATEGORY_NO, AMOUNT,PAYMENT_METHOD_NO) VALUES (2, 120, 2, 2000, 2);
--INSERT INTO CASH_LOG(NO, MEMBER_NO, LOG_CATEGORY_NO, AMOUNT,PAYMENT_METHOD_NO) VALUES (3, 120, 1, 3000, 3);
--INSERT INTO CASH_LOG(NO, MEMBER_NO, LOG_CATEGORY_NO, AMOUNT,PAYMENT_METHOD_NO) VALUES (4, 120, 2, 4000, 4);


-- 자유게시판 카테고리
INSERT INTO FREE_BOARD_CATEGORY (FREE_BOARD_CATEGORY_NO, FREE_BOARD_CATEGORY_NAME)
VALUES (10, '전체');

INSERT INTO FREE_BOARD_CATEGORY (FREE_BOARD_CATEGORY_NO, FREE_BOARD_CATEGORY_NAME)
VALUES (20, '함께해요');

INSERT INTO FREE_BOARD_CATEGORY (FREE_BOARD_CATEGORY_NO, FREE_BOARD_CATEGORY_NAME)
VALUES (30, '궁금해요');

INSERT INTO FREE_BOARD_CATEGORY (FREE_BOARD_CATEGORY_NO, FREE_BOARD_CATEGORY_NAME)
VALUES (40, '얼마에요');

COMMIT;


----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- Create
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

CREATE TABLE CHAT_LOG (
    CHAT_NO             NUMBER          PRIMARY KEY,
    QUOTATION_NO        NUMBER          NOT NULL,
    CHAT_SENDER         NUMBER          NOT NULL,
    CHAT_CONTENT        VARCHAR2(2000),
    CHAT_REQUEST        CHAR(1)         DEFAULT 'X'  CONSTRAINT CHAT_REQUEST_CHECK CHECK (CHAT_REQUEST IN ('O', 'X')),
    CHAT_ATTACHMENT     CHAR(1)         DEFAULT 'X'  CONSTRAINT CHAT_ATTACHMENT_CHECK CHECK (CHAT_ATTACHMENT IN ('O', 'X')),
    CHAT_READ           CHAR(1)         DEFAULT 'X'  CONSTRAINT CHAT_READ_CHECK CHECK (CHAT_READ IN ('O', 'X')),
    CHAT_STATUS         CHAR(1)         DEFAULT 'O'  CONSTRAINT CHAT_STATUS_CHECK CHECK (CHAT_STATUS IN ('O', 'X')),
    CHAT_ENROLL_DATE    TIMESTAMP       DEFAULT SYSDATE
);

CREATE TABLE CHAT_REQUEST_CAT (
    CHAT_REQUEST_CAT_NO     NUMBER      PRIMARY KEY,
    CHAT_REQUEST_CAT_NAME   VARCHAR2(60)
);

CREATE TABLE CHAT_REQUEST (
    REQUEST_NO              NUMBER          PRIMARY KEY,
    CHAT_LOG_NO             NUMBER          NOT NULL,
    REQUEST_CAT_NO          NUMBER          NOT NULL,
    REQUEST_CONTENT         VARCHAR2(3000),
    REQUEST_ENROLL_DATE     TIMESTAMP       DEFAULT SYSDATE,
    REQUEST_STATUS_NO       NUMBER,
    OPTION_NO               NUMBER,
    INPUT_NO                NUMBER
);

CREATE TABLE REQUEST_STATUS (
    REQUEST_STATUS_NO       NUMBER          PRIMARY KEY,
    REQUEST_STATUS_NAME     VARCHAR2(30)    NOT NULL
);




CREATE TABLE CASH_CHARGE_LOG (
    NO                      NUMBER          PRIMARY KEY,
    MEMBER_NO               NUMBER          NOT NULL,
    PAYMENT_METHOD_NO       NUMBER          NOT NULL,
    CHARGE_AMOUNT           NUMBER          NOT NULL,
    CHARGE_DATE             TIMESTAMP       DEFAULT SYSDATE
);

CREATE TABLE POINT_LOG (
    NO                      NUMBER          PRIMARY KEY,
    CASH_CHARGE_LOG_NO      NUMBER          NOT NULL,
    POINT_AMOUNT            NUMBER          NOT NULL
);




CREATE SEQUENCE SEQ_CHAT_LOG_NO             NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CHAT_REQUEST_NO         NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_QUOTATION_OPTION_NO     NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_CASH_CHARGE_NO          NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_POINT_LOG_NO            NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_SALES_LOG_NO            NOCACHE NOCYCLE;


-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- 주문서 상태
INSERT INTO QUOTATION_STATUS
( QUOTATION_STATUS_NO, QUOTATION_STATUS_NAME )
VALUES( 1, '진행중' );
INSERT INTO QUOTATION_STATUS
( QUOTATION_STATUS_NO, QUOTATION_STATUS_NAME )
VALUES( 2, '완료' );
INSERT INTO QUOTATION_STATUS
( QUOTATION_STATUS_NO, QUOTATION_STATUS_NAME )
VALUES( 3, '중지' );
INSERT INTO QUOTATION_STATUS
( QUOTATION_STATUS_NO, QUOTATION_STATUS_NAME )
VALUES( 4, '취소' );

-- 요청 카테고리
INSERT INTO CHAT_REQUEST_CAT VALUES ( 100, '거래 완료');
INSERT INTO CHAT_REQUEST_CAT VALUES ( 200, '거래 취소');
INSERT INTO CHAT_REQUEST_CAT VALUES ( 300, '옵션 추가');
INSERT INTO CHAT_REQUEST_CAT VALUES ( 400, '옵션 취소');
INSERT INTO CHAT_REQUEST_CAT VALUES ( 500, '마감기간 단축');
INSERT INTO CHAT_REQUEST_CAT VALUES ( 600, '마감기간 연장');
INSERT INTO CHAT_REQUEST_CAT VALUES ( 700, '수정 요청');
INSERT INTO CHAT_REQUEST_CAT VALUES ( 800, '선금 요청');

-- 요청 상태
INSERT INTO REQUEST_STATUS VALUES (1, '요청중');
INSERT INTO REQUEST_STATUS VALUES (2, '수락');
INSERT INTO REQUEST_STATUS VALUES (3, '거절');
INSERT INTO REQUEST_STATUS VALUES (4, '만기');

--  SALES_LOG_NO
INSERT INTO SALES_LOG (NO, CATEGORY_NO, SALES, ENROLL_DATE, QUOTATION_NO)
SELECT SEQ_SALES_LOG_NO.NEXTVAL,
       CASE WHEN DBMS_RANDOM.VALUE(0, 1) >= 0.5 THEN 1 ELSE 2 END AS CATEGORY_NO,
       FLOOR(DBMS_RANDOM.VALUE(1000, 10000)) AS SALES,
       TRUNC(SYSDATE - DBMS_RANDOM.VALUE(0, 365)) AS ENROLL_DATE,
       NULL AS QUOTATION_NO
FROM DUAL
CONNECT BY LEVEL <= 20;

-- 매출원(?)  구매수수료:3%, 판매수수료:15%
INSERT INTO SALES_CATEGORY (NO, CATEGORY_NAME, COMMITION) VALUES (1, '구매 수수료', 3);
INSERT INTO SALES_CATEGORY (NO, CATEGORY_NAME, COMMITION) VALUES (2, '판매 수수료', 15);



-- ESTIMATE 테이블 더미 데이터 생성
INSERT INTO "ESTIMATE" (
    "ESTIMATE_NO",
    "FREELANCER_NO",
    "ESTIMATE_CAT_NO",
    "ESTIMATE_TITLE",
    "ESTIMATE_DURATION",
    "ESTIMATE_THUMBNAIL",
    "ESTIMATE_LINE_INTRODUCTION",
    "ESTIMATE_PRICE",
    "ESTIMATE_DETAIL",
    "ESTIMATE_DETAIL_FILE",
    "ESTIMATE_PORTFOLIO",
    "BUSINESS_REGISTRATION_NUMBER",
    "ESTIMATE_STATUS",
    "ESTIMATE_VIEWS"
) VALUES (
    SEQ_ESTIMATE.NEXTVAL, -- ESTIMATE_NO
    100, -- FREELANCER_NO
    20101, -- ESTIMATE_CAT_NO
    '로고 디자인', -- ESTIMATE_TITLE
    '10', -- ESTIMATE_DURATION
    '로고 디자인 썸네일.png', -- ESTIMATE_THUMBNAIL
    '로고 디자인 한줄소개', -- ESTIMATE_LINE_INTRODUCTION
    1000, -- ESTIMATE_PRICE
    '로고 디자인 상세내용', -- ESTIMATE_DETAIL
    '로고 디자인 상세이미지', -- ESTIMATE_DETAIL_FILE
    '로고 디자인 포폴이미지', -- ESTIMATE_PORTFOLIO
    '1234567890', -- BUSINESS_REGISTRATION_NUMBER
    1, -- ESTIMATE_STATUS
    1 -- ESTIMATE_VIEWS
);
INSERT INTO "ESTIMATE" (
    "ESTIMATE_NO",
    "FREELANCER_NO",
    "ESTIMATE_CAT_NO",
    "ESTIMATE_TITLE",
    "ESTIMATE_DURATION",
    "ESTIMATE_THUMBNAIL",
    "ESTIMATE_LINE_INTRODUCTION",
    "ESTIMATE_PRICE",
    "ESTIMATE_DETAIL",
    "ESTIMATE_DETAIL_FILE",
    "ESTIMATE_PORTFOLIO",
    "BUSINESS_REGISTRATION_NUMBER",
    "ESTIMATE_STATUS",
    "ESTIMATE_VIEWS"
) VALUES (
    SEQ_ESTIMATE.NEXTVAL, -- ESTIMATE_NO
    101, -- FREELANCER_NO
    20102, -- ESTIMATE_CAT_NO
    '브랜드 디자인•가이드', -- ESTIMATE_TITLE
    '11', -- ESTIMATE_DURATION
    '브랜드 디자인•가이드 썸네일.png', -- ESTIMATE_THUMBNAIL
    '브랜드 디자인•가이드 한줄소개', -- ESTIMATE_LINE_INTRODUCTION
    2000, -- ESTIMATE_PRICE
    '브랜드 디자인•가이드 상세내용', -- ESTIMATE_DETAIL
    '브랜드 디자인•가이드 상세이미지.png', -- ESTIMATE_DETAIL_FILE
    '브랜드 디자인•가이드 포폴이미지', -- ESTIMATE_PORTFOLIO
    '1234567890', -- BUSINESS_REGISTRATION_NUMBER
    1, -- ESTIMATE_STATUS
    2 -- ESTIMATE_VIEWS
);
INSERT INTO "ESTIMATE" (
    "ESTIMATE_NO",
    "FREELANCER_NO",
    "ESTIMATE_CAT_NO",
    "ESTIMATE_TITLE",
    "ESTIMATE_DURATION",
    "ESTIMATE_THUMBNAIL",
    "ESTIMATE_LINE_INTRODUCTION",
    "ESTIMATE_PRICE",
    "ESTIMATE_DETAIL",
    "ESTIMATE_DETAIL_FILE",
    "ESTIMATE_PORTFOLIO",
    "BUSINESS_REGISTRATION_NUMBER",
    "ESTIMATE_STATUS",
    "ESTIMATE_VIEWS"
) VALUES (
    SEQ_ESTIMATE.NEXTVAL, -- ESTIMATE_NO
    100, -- FREELANCER_NO
    20101, -- ESTIMATE_CAT_NO
    '로고 디자인', -- ESTIMATE_TITLE
    '10', -- ESTIMATE_DURATION
    '로고 디자인 썸네일.png', -- ESTIMATE_THUMBNAIL
    '로고 디자인 한줄소개', -- ESTIMATE_LINE_INTRODUCTION
    2000, -- ESTIMATE_PRICE
    '로고 디자인 상세내용', -- ESTIMATE_DETAIL
    '로고 디자인 상세이미지', -- ESTIMATE_DETAIL_FILE
    '로고 디자인 포폴이미지', -- ESTIMATE_PORTFOLIO
    '1234567890', -- BUSINESS_REGISTRATION_NUMBER
    1, -- ESTIMATE_STATUS
    1 -- ESTIMATE_VIEWS
);
INSERT INTO "ESTIMATE" (
    "ESTIMATE_NO",
    "FREELANCER_NO",
    "ESTIMATE_CAT_NO",
    "ESTIMATE_TITLE",
    "ESTIMATE_DURATION",
    "ESTIMATE_THUMBNAIL",
    "ESTIMATE_LINE_INTRODUCTION",
    "ESTIMATE_PRICE",
    "ESTIMATE_DETAIL",
    "ESTIMATE_DETAIL_FILE",
    "ESTIMATE_PORTFOLIO",
    "BUSINESS_REGISTRATION_NUMBER",
    "ESTIMATE_STATUS",
    "ESTIMATE_VIEWS"
) VALUES (
    SEQ_ESTIMATE.NEXTVAL, -- ESTIMATE_NO
    103, -- FREELANCER_NO
    20201, -- ESTIMATE_CAT_NO
    '웹 디자인', -- ESTIMATE_TITLE
    '13', -- ESTIMATE_DURATION
    '웹 디자인 썸네일.png', -- ESTIMATE_THUMBNAIL
    '웹 디자인 한줄소개', -- ESTIMATE_LINE_INTRODUCTION
    3000, -- ESTIMATE_PRICE
    '웹 디자인 상세내용', -- ESTIMATE_DETAIL
    '웹 디자인 상세이미지', -- ESTIMATE_DETAIL_FILE
    '웹 디자인 포폴이미지', -- ESTIMATE_PORTFOLIO
    '1234567890', -- BUSINESS_REGISTRATION_NUMBER
    1, -- ESTIMATE_STATUS
    3 -- ESTIMATE_VIEWS
);
INSERT INTO "ESTIMATE" (
    "ESTIMATE_NO",
    "FREELANCER_NO",
    "ESTIMATE_CAT_NO",
    "ESTIMATE_TITLE",
    "ESTIMATE_DURATION",
    "ESTIMATE_THUMBNAIL",
    "ESTIMATE_LINE_INTRODUCTION",
    "ESTIMATE_PRICE",
    "ESTIMATE_DETAIL",
    "ESTIMATE_DETAIL_FILE",
    "ESTIMATE_PORTFOLIO",
    "BUSINESS_REGISTRATION_NUMBER",
    "ESTIMATE_STATUS",
    "ESTIMATE_VIEWS"
) VALUES (
    SEQ_ESTIMATE.NEXTVAL, -- ESTIMATE_NO
    103, -- FREELANCER_NO
    20202, -- ESTIMATE_CAT_NO
    '앱•모바일 디자인', -- ESTIMATE_TITLE
    '10', -- ESTIMATE_DURATION
    '앱•모바일 디자인 썸네일.png', -- ESTIMATE_THUMBNAIL
    '앱•모바일 디자인 한줄소개', -- ESTIMATE_LINE_INTRODUCTION
    4000, -- ESTIMATE_PRICE
    '앱•모바일 디자인 상세내용', -- ESTIMATE_DETAIL
    '앱•모바일 디자인 상세이미지', -- ESTIMATE_DETAIL_FILE
    '앱•모바일 디자인 포폴이미지', -- ESTIMATE_PORTFOLIO
    '1234567890', -- BUSINESS_REGISTRATION_NUMBER
    1, -- ESTIMATE_STATUS
    4 -- ESTIMATE_VIEWS
);
INSERT INTO "ESTIMATE" (
    "ESTIMATE_NO",
    "FREELANCER_NO",
    "ESTIMATE_CAT_NO",
    "ESTIMATE_TITLE",
    "ESTIMATE_DURATION",
    "ESTIMATE_THUMBNAIL",
    "ESTIMATE_LINE_INTRODUCTION",
    "ESTIMATE_PRICE",
    "ESTIMATE_DETAIL",
    "ESTIMATE_DETAIL_FILE",
    "ESTIMATE_PORTFOLIO",
    "BUSINESS_REGISTRATION_NUMBER",
    "ESTIMATE_STATUS",
    "ESTIMATE_VIEWS"
) VALUES (
    SEQ_ESTIMATE.NEXTVAL, -- ESTIMATE_NO
    104, -- FREELANCER_NO
    20203, -- ESTIMATE_CAT_NO
    '템플릿형 홈페이지', -- ESTIMATE_TITLE
    '15', -- ESTIMATE_DURATION
    '템플릿형 홈페이지.png', -- ESTIMATE_THUMBNAIL
    '템플릿형 홈페이지', -- ESTIMATE_LINE_INTRODUCTION
    5000, -- ESTIMATE_PRICE
    '템플릿형 홈페이지 상세내용', -- ESTIMATE_DETAIL
    '템플릿형 홈페이지 상세이미지', -- ESTIMATE_DETAIL_FILE
    '템플릿형 홈페이지 포폴이미지', -- ESTIMATE_PORTFOLIO
    '1234567890', -- BUSINESS_REGISTRATION_NUMBER
    1, -- ESTIMATE_STATUS
    5 -- ESTIMATE_VIEWS
);
INSERT INTO "ESTIMATE" (
    "ESTIMATE_NO",
    "FREELANCER_NO",
    "ESTIMATE_CAT_NO",
    "ESTIMATE_TITLE",
    "ESTIMATE_DURATION",
    "ESTIMATE_THUMBNAIL",
    "ESTIMATE_LINE_INTRODUCTION",
    "ESTIMATE_PRICE",
    "ESTIMATE_DETAIL",
    "ESTIMATE_DETAIL_FILE",
    "ESTIMATE_PORTFOLIO",
    "BUSINESS_REGISTRATION_NUMBER",
    "ESTIMATE_STATUS",
    "ESTIMATE_VIEWS"
) VALUES (
    SEQ_ESTIMATE.NEXTVAL, -- ESTIMATE_NO
    105, -- FREELANCER_NO
    20204, -- ESTIMATE_CAT_NO
    '아이콘•버튼', -- ESTIMATE_TITLE
    '15', -- ESTIMATE_DURATION
    '아이콘•버튼.png', -- ESTIMATE_THUMBNAIL
    '아이콘•버튼', -- ESTIMATE_LINE_INTRODUCTION
    6000, -- ESTIMATE_PRICE
    '아이콘•버튼 상세내용', -- ESTIMATE_DETAIL
    '아이콘•버튼 상세이미지', -- ESTIMATE_DETAIL_FILE
    '아이콘•버튼 포폴이미지', -- ESTIMATE_PORTFOLIO
    '1234567890', -- BUSINESS_REGISTRATION_NUMBER
    1, -- ESTIMATE_STATUS
    6 -- ESTIMATE_VIEWS
);
INSERT INTO "ESTIMATE" (
    "ESTIMATE_NO",
    "FREELANCER_NO",
    "ESTIMATE_CAT_NO",
    "ESTIMATE_TITLE",
    "ESTIMATE_DURATION",
    "ESTIMATE_THUMBNAIL",
    "ESTIMATE_LINE_INTRODUCTION",
    "ESTIMATE_PRICE",
    "ESTIMATE_DETAIL",
    "ESTIMATE_DETAIL_FILE",
    "ESTIMATE_PORTFOLIO",
    "BUSINESS_REGISTRATION_NUMBER",
    "ESTIMATE_STATUS",
    "ESTIMATE_VIEWS"
) VALUES (
    SEQ_ESTIMATE.NEXTVAL, -- ESTIMATE_NO
    106, -- FREELANCER_NO
    20301, -- ESTIMATE_CAT_NO
    '일러스트', -- ESTIMATE_TITLE
    '16', -- ESTIMATE_DURATION
    '일러스트.png', -- ESTIMATE_THUMBNAIL
    '일러스트', -- ESTIMATE_LINE_INTRODUCTION
    7000, -- ESTIMATE_PRICE
    '일러스트 상세내용', -- ESTIMATE_DETAIL
    '일러스트 상세이미지', -- ESTIMATE_DETAIL_FILE
    '일러스트 포폴이미지', -- ESTIMATE_PORTFOLIO
    '1234567890', -- BUSINESS_REGISTRATION_NUMBER
    1, -- ESTIMATE_STATUS
    7 -- ESTIMATE_VIEWS
);
INSERT INTO "ESTIMATE" (
    "ESTIMATE_NO",
    "FREELANCER_NO",
    "ESTIMATE_CAT_NO",
    "ESTIMATE_TITLE",
    "ESTIMATE_DURATION",
    "ESTIMATE_THUMBNAIL",
    "ESTIMATE_LINE_INTRODUCTION",
    "ESTIMATE_PRICE",
    "ESTIMATE_DETAIL",
    "ESTIMATE_DETAIL_FILE",
    "ESTIMATE_PORTFOLIO",
    "BUSINESS_REGISTRATION_NUMBER",
    "ESTIMATE_STATUS",
    "ESTIMATE_VIEWS"
) VALUES (
    SEQ_ESTIMATE.NEXTVAL, -- ESTIMATE_NO
    107, -- FREELANCER_NO
    20302, -- ESTIMATE_CAT_NO
    '캐리커쳐', -- ESTIMATE_TITLE
    '16', -- ESTIMATE_DURATION
    '캐리커쳐.png', -- ESTIMATE_THUMBNAIL
    '캐리커쳐', -- ESTIMATE_LINE_INTRODUCTION
    8000, -- ESTIMATE_PRICE
    '캐리커쳐 상세내용', -- ESTIMATE_DETAIL
    '캐리커쳐 상세이미지', -- ESTIMATE_DETAIL_FILE
    '캐리커쳐 포폴이미지', -- ESTIMATE_PORTFOLIO
    '1234567890', -- BUSINESS_REGISTRATION_NUMBER
    1, -- ESTIMATE_STATUS
    8 -- ESTIMATE_VIEWS
);
INSERT INTO "ESTIMATE" (
    "ESTIMATE_NO",
    "FREELANCER_NO",
    "ESTIMATE_CAT_NO",
    "ESTIMATE_TITLE",
    "ESTIMATE_DURATION",
    "ESTIMATE_THUMBNAIL",
    "ESTIMATE_LINE_INTRODUCTION",
    "ESTIMATE_PRICE",
    "ESTIMATE_DETAIL",
    "ESTIMATE_DETAIL_FILE",
    "ESTIMATE_PORTFOLIO",
    "BUSINESS_REGISTRATION_NUMBER",
    "ESTIMATE_STATUS",
    "ESTIMATE_VIEWS"
) VALUES (
    SEQ_ESTIMATE.NEXTVAL, -- ESTIMATE_NO
    108, -- FREELANCER_NO
    20303, -- ESTIMATE_CAT_NO
    '웹툰•콘티', -- ESTIMATE_TITLE
    '17', -- ESTIMATE_DURATION
    '웹툰•콘티.png', -- ESTIMATE_THUMBNAIL
    '웹툰•콘티', -- ESTIMATE_LINE_INTRODUCTION
    9000, -- ESTIMATE_PRICE
    '웹툰•콘티 상세내용', -- ESTIMATE_DETAIL
    '웹툰•콘티 상세이미지', -- ESTIMATE_DETAIL_FILE
    '웹툰•콘티 포폴이미지', -- ESTIMATE_PORTFOLIO
    '1234567890', -- BUSINESS_REGISTRATION_NUMBER
    1, -- ESTIMATE_STATUS
    9 -- ESTIMATE_VIEWS
);

-- 배너
INSERT INTO BANNER (BANNER_NO, BANNER_STATUS) VALUES(1, 'X');
INSERT INTO BANNER (BANNER_NO, BANNER_STATUS) VALUES(2, 'X');
INSERT INTO BANNER (BANNER_NO, BANNER_STATUS) VALUES(3, 'X');
INSERT INTO BANNER (BANNER_NO, BANNER_STATUS) VALUES(4, 'X');

-- 신고 카테고리
INSERT INTO REPORT_CATEGORY (RPT_CAT_NO, RPT_CAT_NAME) VALUES (1, '스팸/도배');
INSERT INTO REPORT_CATEGORY (RPT_CAT_NO, RPT_CAT_NAME) VALUES (2, '불법');
INSERT INTO REPORT_CATEGORY (RPT_CAT_NO, RPT_CAT_NAME) VALUES (3, '혐오');
INSERT INTO REPORT_CATEGORY (RPT_CAT_NO, RPT_CAT_NAME) VALUES (4, '욕설');
INSERT INTO REPORT_CATEGORY (RPT_CAT_NO, RPT_CAT_NAME) VALUES (5, '개인정보 노출');
INSERT INTO REPORT_CATEGORY (RPT_CAT_NO, RPT_CAT_NAME) VALUES (6, '저작권 침해');
